<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_lHugYKVREfGljdYClBXUfw" name="MiDiagrama" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_lHugYaVREfGljdYClBXUfw" name="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_lHugYqVREfGljdYClBXUfw" name="Municipio" actor="_ffzZIKVSEfGljdYClBXUfw">
        <elements xmi:type="process:StartEvent" xmi:id="_lHugY6VREfGljdYClBXUfw" name="Inicio " outgoing="_lHugeKVREfGljdYClBXUfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lHugZKVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lHugZaVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lHugZqVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_lHugZ6VREfGljdYClBXUfw" name="Registro de emergencia" outgoing="_id2zwKVUEfGljdYClBXUfw" incoming="_lHugeKVREfGljdYClBXUfw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lHugaKVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lHugaaVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lHugaqVREfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_lHuga6VREfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_lHugbKVREfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_lHugbaVREfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_lHugbqVREfGljdYClBXUfw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_lHugb6VREfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_lHugcKVREfGljdYClBXUfw">
            <targetForm xmi:type="expression:Expression" xmi:id="_lHugcaVREfGljdYClBXUfw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_lHugcqVREfGljdYClBXUfw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_lHugc6VREfGljdYClBXUfw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_RvKo4KVUEfGljdYClBXUfw" name="Centro Coordinador Regional" actor="_VdPdIKVUEfGljdYClBXUfw">
        <elements xmi:type="process:ServiceTask" xmi:id="_f11BkKVUEfGljdYClBXUfw" name="Recibe alerta " outgoing="_Mi14gKVVEfGljdYClBXUfw" incoming="_id2zwKVUEfGljdYClBXUfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_f11ooaVUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_f11ooKVUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_f11ooqVUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_f11oo6VUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_f11opKVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_f11opaVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_f11op6VUEfGljdYClBXUfw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_f11opqVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_jWlLgKVUEfGljdYClBXUfw" name="Publica en red" outgoing="_skny8KVVEfGljdYClBXUfw" incoming="_NCXtIKVVEfGljdYClBXUfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jWlLgqVUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jWlLgaVUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jWlLg6VUEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jWlLhKVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jWlLhaVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jWlLhqVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jWlLiKVUEfGljdYClBXUfw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jWlLh6VUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_G1AzAKVVEfGljdYClBXUfw" name="Desglosa en &quot;Lotes Necesidades&quot;" outgoing="_NCXtIKVVEfGljdYClBXUfw" incoming="_Mi14gKVVEfGljdYClBXUfw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G1BaEaVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G1BaEKVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G1BaEqVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_G1BaE6VVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_G1BaFKVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_G1BaFaVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_G1BaF6VVEfGljdYClBXUfw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_G1BaFqVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_G1BaGaVVEfGljdYClBXUfw">
            <targetForm xmi:type="expression:Expression" xmi:id="_G1BaGqVVEfGljdYClBXUfw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_G1BaGKVVEfGljdYClBXUfw"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_G1BaG6VVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_rukUsKVVEfGljdYClBXUfw" name="Fin1" incoming="_skny8KVVEfGljdYClBXUfw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ruli0KVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ruk7wKVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ruli0aVVEfGljdYClBXUfw" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_lHugdKVREfGljdYClBXUfw">
        <targetForm xmi:type="expression:Expression" xmi:id="_lHugdaVREfGljdYClBXUfw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_lHugdqVREfGljdYClBXUfw">
        <targetForm xmi:type="expression:Expression" xmi:id="_lHugd6VREfGljdYClBXUfw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_lHugeKVREfGljdYClBXUfw" target="_lHugZ6VREfGljdYClBXUfw" source="_lHugY6VREfGljdYClBXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_lHugeaVREfGljdYClBXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_lHugeqVREfGljdYClBXUfw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_id2zwKVUEfGljdYClBXUfw" target="_f11BkKVUEfGljdYClBXUfw" source="_lHugZ6VREfGljdYClBXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_id3a0KVUEfGljdYClBXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_id3a0aVUEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Mi14gKVVEfGljdYClBXUfw" target="_G1AzAKVVEfGljdYClBXUfw" source="_f11BkKVUEfGljdYClBXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Mi2fkKVVEfGljdYClBXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Mi2fkaVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NCXtIKVVEfGljdYClBXUfw" target="_jWlLgKVUEfGljdYClBXUfw" source="_G1AzAKVVEfGljdYClBXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NCYUMKVVEfGljdYClBXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_NCYUMaVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_skny8KVVEfGljdYClBXUfw" target="_rukUsKVVEfGljdYClBXUfw" source="_jWlLgKVUEfGljdYClBXUfw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_skny8aVVEfGljdYClBXUfw"/>
        <condition xmi:type="expression:Expression" xmi:id="_skny8qVVEfGljdYClBXUfw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_lHuge6VREfGljdYClBXUfw" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_ffzZIKVSEfGljdYClBXUfw" name="Municipio"/>
      <actors xmi:type="process:Actor" xmi:id="_VdPdIKVUEfGljdYClBXUfw" name="Centro Coordinador Regional"/>
      <contract xmi:type="process:Contract" xmi:id="_lHugfKVREfGljdYClBXUfw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lHugfaVREfGljdYClBXUfw">
        <name xmi:type="expression:Expression" xmi:id="_lHugfqVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lHugf6VREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lHuggKVREfGljdYClBXUfw">
        <name xmi:type="expression:Expression" xmi:id="_lHuggaVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lHuggqVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lHugg6VREfGljdYClBXUfw">
        <name xmi:type="expression:Expression" xmi:id="_lHughKVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lHughaVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lHughqVREfGljdYClBXUfw">
        <name xmi:type="expression:Expression" xmi:id="_lHugh6VREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lHugiKVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_lHugiaVREfGljdYClBXUfw">
        <name xmi:type="expression:Expression" xmi:id="_lHugiqVREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_lHugi6VREfGljdYClBXUfw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_lHugjKVREfGljdYClBXUfw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_lHugjaVREfGljdYClBXUfw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_lHugjqVREfGljdYClBXUfw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_lHugj6VREfGljdYClBXUfw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_lHugkKVREfGljdYClBXUfw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_lHugkaVREfGljdYClBXUfw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_lHugkqVREfGljdYClBXUfw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_lHugk6VREfGljdYClBXUfw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_lHuglKVREfGljdYClBXUfw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_lHuglaVREfGljdYClBXUfw" type="Process" element="_lHugYKVREfGljdYClBXUfw" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_lHuglqVREfGljdYClBXUfw" type="2007" element="_lHugYaVREfGljdYClBXUfw">
      <children xmi:type="notation:DecorationNode" xmi:id="_lHugl6VREfGljdYClBXUfw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_lHugmKVREfGljdYClBXUfw" type="7001">
        <children xmi:type="notation:Node" xmi:id="_lHugmaVREfGljdYClBXUfw" type="3007" element="_lHugYqVREfGljdYClBXUfw">
          <children xmi:type="notation:DecorationNode" xmi:id="_lHugmqVREfGljdYClBXUfw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_lHugm6VREfGljdYClBXUfw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_lHugnKVREfGljdYClBXUfw" type="3005" element="_lHugZ6VREfGljdYClBXUfw" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_lHugnaVREfGljdYClBXUfw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lHugnqVREfGljdYClBXUfw" x="160" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lHugn6VREfGljdYClBXUfw" type="3002" element="_lHugY6VREfGljdYClBXUfw" fontName="Ubuntu Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_lHugoKVREfGljdYClBXUfw" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lHugoaVREfGljdYClBXUfw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lHugoqVREfGljdYClBXUfw" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_lHugo6VREfGljdYClBXUfw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_lHugpKVREfGljdYClBXUfw" fontName="Ubuntu Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_lHugpaVREfGljdYClBXUfw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_lHugpqVREfGljdYClBXUfw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lHugp6VREfGljdYClBXUfw" x="49" y="10" width="1296" height="237"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_RvLP8KVUEfGljdYClBXUfw" type="3007" element="_RvKo4KVUEfGljdYClBXUfw">
          <children xmi:type="notation:DecorationNode" xmi:id="_RvL3AKVUEfGljdYClBXUfw" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_RvL3AaVUEfGljdYClBXUfw" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_f12PsKVUEfGljdYClBXUfw" type="3027" element="_f11BkKVUEfGljdYClBXUfw" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f122wKVUEfGljdYClBXUfw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f12PsaVUEfGljdYClBXUfw" x="174" y="67" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_jWnAsKVUEfGljdYClBXUfw" type="3027" element="_jWlLgKVUEfGljdYClBXUfw" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_jWnAsqVUEfGljdYClBXUfw" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_jWnAsaVUEfGljdYClBXUfw" x="668" y="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_G1DPQKVVEfGljdYClBXUfw" type="3005" element="_G1AzAKVVEfGljdYClBXUfw" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_G1DPQqVVEfGljdYClBXUfw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_G1DPQaVVEfGljdYClBXUfw" x="385" y="72" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_run_EKVVEfGljdYClBXUfw" type="3062" element="_rukUsKVVEfGljdYClBXUfw" fontName="Ubuntu Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_ruomIKVVEfGljdYClBXUfw" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ruomIaVVEfGljdYClBXUfw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_run_EaVVEfGljdYClBXUfw" x="926" y="90"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_RvLP8aVUEfGljdYClBXUfw"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_RvLP8qVUEfGljdYClBXUfw" fontName="Ubuntu Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_RvLP86VUEfGljdYClBXUfw"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_RvL3AqVUEfGljdYClBXUfw"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RvLP9KVUEfGljdYClBXUfw" x="200" y="164"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_lHugqKVREfGljdYClBXUfw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_lHugqaVREfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_lHugqqVREfGljdYClBXUfw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_lHugq6VREfGljdYClBXUfw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lHugrKVREfGljdYClBXUfw" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_lHvHcKVREfGljdYClBXUfw"/>
    <edges xmi:type="notation:Connector" xmi:id="_lHvHcaVREfGljdYClBXUfw" type="4001" element="_lHugeKVREfGljdYClBXUfw" source="_lHugn6VREfGljdYClBXUfw" target="_lHugnKVREfGljdYClBXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_lHvHcqVREfGljdYClBXUfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_lHvHc6VREfGljdYClBXUfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_lHvHdKVREfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_lHvHdaVREfGljdYClBXUfw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_id3a0qVUEfGljdYClBXUfw" type="4001" element="_id2zwKVUEfGljdYClBXUfw" source="_lHugnKVREfGljdYClBXUfw" target="_f12PsKVUEfGljdYClBXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_id4B4KVUEfGljdYClBXUfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_id4B4aVUEfGljdYClBXUfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_id3a06VUEfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_id3a1KVUEfGljdYClBXUfw" points="[0, 30, 0, -194]$[-3, 214, -3, -10]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_id5QAKVUEfGljdYClBXUfw" id="(0.46,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Mi3tsKVVEfGljdYClBXUfw" type="4001" element="_Mi14gKVVEfGljdYClBXUfw" source="_f12PsKVUEfGljdYClBXUfw" target="_G1DPQKVVEfGljdYClBXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Mi3ts6VVEfGljdYClBXUfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Mi4UwKVVEfGljdYClBXUfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Mi3tsaVVEfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Mi3tsqVVEfGljdYClBXUfw" points="[9, -2, -99, 0]$[100, -2, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mi6xAKVVEfGljdYClBXUfw" id="(0.925,0.6333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Mi6xAaVVEfGljdYClBXUfw" id="(0.06666666666666667,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NCZiUKVVEfGljdYClBXUfw" type="4001" element="_NCXtIKVVEfGljdYClBXUfw" source="_G1DPQKVVEfGljdYClBXUfw" target="_jWnAsKVUEfGljdYClBXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NCaJYKVVEfGljdYClBXUfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NCawcKVVEfGljdYClBXUfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NCZiUaVVEfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NCZiUqVVEfGljdYClBXUfw" points="[9, 1, -172, 0]$[172, 1, -9, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NCea0KVVEfGljdYClBXUfw" id="(0.925,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NCea0aVVEfGljdYClBXUfw" id="(0.09,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_skny86VVEfGljdYClBXUfw" type="4001" element="_skny8KVVEfGljdYClBXUfw" source="_jWnAsKVUEfGljdYClBXUfw" target="_run_EKVVEfGljdYClBXUfw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_skny9qVVEfGljdYClBXUfw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_skny96VVEfGljdYClBXUfw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_skny9KVVEfGljdYClBXUfw" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_skny9aVVEfGljdYClBXUfw" points="[11, 0, -173, -10]$[180, 24, -4, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_skpBEKVVEfGljdYClBXUfw" id="(0.89,0.42)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
