<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_SErHMKVGEfGHdoHzI9CAtQ" name="AdjudicacionYNotificacion" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_SErHMaVGEfGHdoHzI9CAtQ" name="RescueSync" displayName="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_CuCawKVOEfGHdoHzI9CAtQ" name="Sistema">
        <elements xmi:type="process:ServiceTask" xmi:id="_GEL3MKVOEfGHdoHzI9CAtQ" name="Registrar compromiso" incoming="_IX-ewKVOEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GEL3MqVOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GEL3MaVOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GEL3M6VOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GEL3NKVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GEL3NaVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GEL3NqVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GEL3OKVOEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GEL3N6VOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_SErHMqVGEfGHdoHzI9CAtQ" name="Municipio" actor="_SErHS6VGEfGHdoHzI9CAtQ">
        <elements xmi:type="process:StartEvent" xmi:id="_SErHM6VGEfGHdoHzI9CAtQ" name="Start1" outgoing="_SErHSKVGEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SErHNKVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SErHNaVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SErHNqVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_fB7yYKVHEfGHdoHzI9CAtQ" name="Ver ofertas validadas" outgoing="_dxPNQKVMEfGHdoHzI9CAtQ" incoming="_SErHSKVGEfGHdoHzI9CAtQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SErHOKVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SErHOaVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SErHOqVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SErHO6VGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SErHPKVGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SErHPaVGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SErHPqVGEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SErHP6VGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_fB8ZeaVHEfGHdoHzI9CAtQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_fB8ZeqVHEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_fB8ZeKVHEfGHdoHzI9CAtQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_fB8Ze6VHEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_iLo8AKVMEfGHdoHzI9CAtQ" name="Gateway1" outgoing="_juKesKVMEfGHdoHzI9CAtQ _IX-ewKVOEfGHdoHzI9CAtQ" incoming="_iLwQwKVMEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iLvCoaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iLvCoKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iLvCoqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_o9jUsKVMEfGHdoHzI9CAtQ" name="Seleccionar oferta(s)" outgoing="_iLwQwKVMEfGHdoHzI9CAtQ" incoming="_dxPNQKVMEfGHdoHzI9CAtQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dxN_IaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dxN_IKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dxN_IqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dxN_I6VMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dxN_JKVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dxN_JaVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dxN_J6VMEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dxN_JqVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_o9j7xKVMEfGHdoHzI9CAtQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_o9j7xaVMEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_o9j7w6VMEfGHdoHzI9CAtQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_o9j7xqVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_w37KQKVMEfGHdoHzI9CAtQ" name="End1" incoming="_w39mgKVMEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w37xUaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w37xUKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w37xUqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_mPfWgKVNEfGHdoHzI9CAtQ" name="Notificar ONG(s)" outgoing="_w39mgKVMEfGHdoHzI9CAtQ _1wkewKVNEfGHdoHzI9CAtQ" incoming="_juKesKVMEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_juIpgqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_juIpgaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_juIpg6VMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_juIphKVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_juIphaVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_juIphqVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_juIpiKVMEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_juIph6VMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_e7oHUKVNEfGHdoHzI9CAtQ" name="ONG">
        <elements xmi:type="process:ReceiveTask" xmi:id="_m_BWAKVNEfGHdoHzI9CAtQ" name="Recibir notificación" incoming="_1wkewKVNEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iMUcAKVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iMT08aVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iMUcAaVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iMUcAqVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iMUcA6VNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iMUcBKVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iMUcBqVNEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iMUcBaVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_nn7JEKVNEfGHdoHzI9CAtQ">
            <expressions xmi:type="expression:ListExpression" xmi:id="_n7zHUKVNEfGHdoHzI9CAtQ">
              <expressions xmi:type="expression:Expression" xmi:id="_n7zHUaVNEfGHdoHzI9CAtQ" content=""/>
              <expressions xmi:type="expression:Expression" xmi:id="_n7zHUqVNEfGHdoHzI9CAtQ"/>
            </expressions>
          </correlation>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_SErHRKVGEfGHdoHzI9CAtQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_SErHRaVGEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_SErHRqVGEfGHdoHzI9CAtQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_SErHR6VGEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SErHSKVGEfGHdoHzI9CAtQ" target="_fB7yYKVHEfGHdoHzI9CAtQ" source="_SErHM6VGEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SErHSaVGEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SErHSqVGEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dxPNQKVMEfGHdoHzI9CAtQ" target="_o9jUsKVMEfGHdoHzI9CAtQ" source="_fB7yYKVHEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dxPNQaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dxPNQqVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iLwQwKVMEfGHdoHzI9CAtQ" target="_iLo8AKVMEfGHdoHzI9CAtQ" source="_o9jUsKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iLwQwaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_iLwQwqVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_juKesKVMEfGHdoHzI9CAtQ" target="_mPfWgKVNEfGHdoHzI9CAtQ" source="_iLo8AKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_juKesaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_juKesqVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w39mgKVMEfGHdoHzI9CAtQ" target="_w37KQKVMEfGHdoHzI9CAtQ" source="_mPfWgKVNEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w39mgaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_w3-NkKVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1wkewKVNEfGHdoHzI9CAtQ" target="_m_BWAKVNEfGHdoHzI9CAtQ" source="_mPfWgKVNEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1wlF0KVNEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1wlF0aVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IX-ewKVOEfGHdoHzI9CAtQ" target="_GEL3MKVOEfGHdoHzI9CAtQ" source="_iLo8AKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IX-ewaVOEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_IX-ewqVOEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_SErHS6VGEfGHdoHzI9CAtQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_SErHTKVGEfGHdoHzI9CAtQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHTaVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHTqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHT6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHUKVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHUaVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHUqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHU6VGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHVKVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHVaVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHVqVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHV6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHWKVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHWaVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHWqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHW6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_SErHXKVGEfGHdoHzI9CAtQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_SErHXaVGEfGHdoHzI9CAtQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_SErHXqVGEfGHdoHzI9CAtQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_SErHX6VGEfGHdoHzI9CAtQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_SErHYKVGEfGHdoHzI9CAtQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_SErHYaVGEfGHdoHzI9CAtQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_SErHYqVGEfGHdoHzI9CAtQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_SErHY6VGEfGHdoHzI9CAtQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_SErHZKVGEfGHdoHzI9CAtQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_SErHZaVGEfGHdoHzI9CAtQ" type="Process" element="_SErHMKVGEfGHdoHzI9CAtQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_SErHZqVGEfGHdoHzI9CAtQ" type="2007" element="_SErHMaVGEfGHdoHzI9CAtQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHZ6VGEfGHdoHzI9CAtQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHaKVGEfGHdoHzI9CAtQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_SErHaaVGEfGHdoHzI9CAtQ" type="3007" element="_SErHMqVGEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_SErHaqVGEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_SErHa6VGEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_SErHb6VGEfGHdoHzI9CAtQ" type="3002" element="_SErHM6VGEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SErHcKVGEfGHdoHzI9CAtQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SErHcaVGEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHcqVGEfGHdoHzI9CAtQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fB9AgKVHEfGHdoHzI9CAtQ" type="3005" element="_fB7yYKVHEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_fB9nkKVHEfGHdoHzI9CAtQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fB9AgaVHEfGHdoHzI9CAtQ" x="118" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iLvpsKVMEfGHdoHzI9CAtQ" type="3009" element="_iLo8AKVMEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iLvpsqVMEfGHdoHzI9CAtQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iLvps6VMEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iLvpsaVMEfGHdoHzI9CAtQ" x="429" y="66"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o9j7x6VMEfGHdoHzI9CAtQ" type="3005" element="_o9jUsKVMEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o9ki0KVMEfGHdoHzI9CAtQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o9j7yKVMEfGHdoHzI9CAtQ" x="270" y="60" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w38YYKVMEfGHdoHzI9CAtQ" type="3003" element="_w37KQKVMEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w38YYqVMEfGHdoHzI9CAtQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w38_cKVMEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w38YYaVMEfGHdoHzI9CAtQ" x="652" y="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_mPf9kaVNEfGHdoHzI9CAtQ" type="3025" element="_mPfWgKVNEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_mPf9k6VNEfGHdoHzI9CAtQ" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_mPf9kqVNEfGHdoHzI9CAtQ" x="516" y="66" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_SErHc6VGEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_SErHdKVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_SErHdaVGEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_SErHdqVGEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHd6VGEfGHdoHzI9CAtQ" x="48" y="10" width="777" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_e7pVcKVNEfGHdoHzI9CAtQ" type="3007" element="_e7oHUKVNEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_e7pVdaVNEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_e7pVdqVNEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_m_B9FqVNEfGHdoHzI9CAtQ" type="3026" element="_m_BWAKVNEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_m_B9GKVNEfGHdoHzI9CAtQ" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m_B9F6VNEfGHdoHzI9CAtQ" x="506" y="43" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_e7pVcaVNEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_e7pVcqVNEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_e7pVc6VNEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_e7pVd6VNEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e7pVdKVNEfGHdoHzI9CAtQ" x="113" y="176"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_CuDo4KVOEfGHdoHzI9CAtQ" type="3007" element="_CuCawKVOEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_CuDo5aVOEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_CuDo5qVOEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_GEL3OaVOEfGHdoHzI9CAtQ" type="3027" element="_GEL3MKVOEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GEMeQKVOEfGHdoHzI9CAtQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GEL3OqVOEfGHdoHzI9CAtQ" x="519" y="46" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_CuDo4aVOEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_CuDo4qVOEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_CuDo46VOEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_CuDo56VOEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CuDo5KVOEfGHdoHzI9CAtQ" x="48" y="10" width="777" height="156"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_SErHeKVGEfGHdoHzI9CAtQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_SErHeaVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_SErHeqVGEfGHdoHzI9CAtQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_SErHe6VGEfGHdoHzI9CAtQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHfKVGEfGHdoHzI9CAtQ" width="800" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_SErHfaVGEfGHdoHzI9CAtQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_SErHfqVGEfGHdoHzI9CAtQ" type="4001" element="_SErHSKVGEfGHdoHzI9CAtQ" source="_SErHb6VGEfGHdoHzI9CAtQ" target="_fB9AgKVHEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHf6VGEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SErHgKVGEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SErHgaVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SErHgqVGEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dxP0UKVMEfGHdoHzI9CAtQ" type="4001" element="_dxPNQKVMEfGHdoHzI9CAtQ" source="_fB9AgKVHEfGHdoHzI9CAtQ" target="_o9j7x6VMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dxP0U6VMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dxP0VKVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dxP0UaVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dxP0UqVMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iLw30KVMEfGHdoHzI9CAtQ" type="4001" element="_iLwQwKVMEfGHdoHzI9CAtQ" source="_o9j7x6VMEfGHdoHzI9CAtQ" target="_iLvpsKVMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iLw306VMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iLw31KVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iLw30aVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iLw30qVMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_juKes6VMEfGHdoHzI9CAtQ" type="4001" element="_juKesKVMEfGHdoHzI9CAtQ" source="_iLvpsKVMEfGHdoHzI9CAtQ" target="_mPf9kaVNEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_juLFwKVMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_juLFwaVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_juKetKVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_juKetaVMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w3-NkaVMEfGHdoHzI9CAtQ" type="4001" element="_w39mgKVMEfGHdoHzI9CAtQ" source="_mPf9kaVNEfGHdoHzI9CAtQ" target="_w38YYKVMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w3-0oKVMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w3-0oaVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w3-NkqVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w3-Nk6VMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1wlF0qVNEfGHdoHzI9CAtQ" type="4001" element="_1wkewKVNEfGHdoHzI9CAtQ" source="_mPf9kaVNEfGHdoHzI9CAtQ" target="_m_B9FqVNEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1wls4KVNEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1wls4aVNEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1wlF06VNEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1wlF1KVNEfGHdoHzI9CAtQ" points="[-52, 25, 1, -179]$[-52, 202, 1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1wniEKVNEfGHdoHzI9CAtQ" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1wniEaVNEfGHdoHzI9CAtQ" id="(0.475,0.03333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IX_F0KVOEfGHdoHzI9CAtQ" type="4001" element="_IX-ewKVOEfGHdoHzI9CAtQ" source="_iLvpsKVMEfGHdoHzI9CAtQ" target="_GEL3OaVOEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IX_F06VOEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IX_s4KVOEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IX_F0aVOEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IX_F0qVOEfGHdoHzI9CAtQ" points="[-22, -28, -78, 145]$[-22, -109, -78, 64]$[107, -109, 51, 64]$[107, -144, 51, 29]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IYBiEKVOEfGHdoHzI9CAtQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IYBiEaVOEfGHdoHzI9CAtQ" id="(0.08,0.52)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
