<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_SErHMKVGEfGHdoHzI9CAtQ" name="AdjudicacionYNotificacion" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_SErHMaVGEfGHdoHzI9CAtQ" name="RescueSync" displayName="RescueSync">
      <elements xmi:type="process:Lane" xmi:id="_CuCawKVOEfGHdoHzI9CAtQ" name="Sistema">
        <elements xmi:type="process:ServiceTask" xmi:id="_GEL3MKVOEfGHdoHzI9CAtQ" name="Registrar compromiso" incoming="_IX-ewKVOEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_GEL3MqVOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_GEL3MaVOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_GEL3M6VOEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_GEL3NKVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_GEL3NaVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_GEL3NqVOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_GEL3OKVOEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_GEL3N6VOEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_SErHMqVGEfGHdoHzI9CAtQ" name="Municipio" actor="_6iL6AKVVEfGXn7QjRZTm_Q">
        <elements xmi:type="process:StartEvent" xmi:id="_SErHM6VGEfGHdoHzI9CAtQ" name="Iniciar adjudicación" outgoing="_SErHSKVGEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SErHNKVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SErHNaVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SErHNqVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_iLo8AKVMEfGHdoHzI9CAtQ" name="Gateway1" outgoing="_IX-ewKVOEfGHdoHzI9CAtQ _p0m3gKVXEfGXn7QjRZTm_Q" incoming="_iLwQwKVMEfGHdoHzI9CAtQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iLvCoaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iLvCoKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iLvCoqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_o9jUsKVMEfGHdoHzI9CAtQ" name="Seleccionar oferta(s)" outgoing="_iLwQwKVMEfGHdoHzI9CAtQ" incoming="_dxPNQKVMEfGHdoHzI9CAtQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dxN_IaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dxN_IKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dxN_IqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dxN_I6VMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dxN_JKVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dxN_JaVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dxN_J6VMEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dxN_JqVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_o9j7xKVMEfGHdoHzI9CAtQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_o9j7xaVMEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_o9j7w6VMEfGHdoHzI9CAtQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_o9j7xqVMEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_w37KQKVMEfGHdoHzI9CAtQ" name="Adjudicación finalizada" incoming="_1SDyQKVXEfGXn7QjRZTm_Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w37xUaVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w37xUKVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w37xUqVMEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_9ggsUKVVEfGXn7QjRZTm_Q" name="Ver ofertas validadas" outgoing="_dxPNQKVMEfGHdoHzI9CAtQ" incoming="_SErHSKVGEfGHdoHzI9CAtQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_SErHOKVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_SErHOaVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_SErHOqVGEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_SErHO6VGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_SErHPKVGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_SErHPaVGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_SErHPqVGEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_SErHP6VGEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9gh6dqVVEfGXn7QjRZTm_Q">
            <targetForm xmi:type="expression:Expression" xmi:id="_9gh6d6VVEfGXn7QjRZTm_Q" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9gh6daVVEfGXn7QjRZTm_Q"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9gh6eKVVEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:SendTask" xmi:id="_s-G_EKVXEfGXn7QjRZTm_Q" name="Enviar notificación a ONG(s)" outgoing="_tk-KwKVXEfGXn7QjRZTm_Q _1SDyQKVXEfGXn7QjRZTm_Q" incoming="_p0m3gKVXEfGXn7QjRZTm_Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_p0lCUaVXEfGXn7QjRZTm_Q" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_p0lCUKVXEfGXn7QjRZTm_Q" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_p0lCUqVXEfGXn7QjRZTm_Q" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_p0lCU6VXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_p0lCVKVXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_p0lCVaVXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_p0lCV6VXEfGXn7QjRZTm_Q" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_p0lCVqVXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_e7oHUKVNEfGHdoHzI9CAtQ" name="ONG">
        <elements xmi:type="process:ReceiveTask" xmi:id="_m_BWAKVNEfGHdoHzI9CAtQ" name="Recibir notificación" incoming="_tk-KwKVXEfGXn7QjRZTm_Q">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iMUcAKVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iMT08aVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iMUcAaVNEfGHdoHzI9CAtQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iMUcAqVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iMUcA6VNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iMUcBKVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iMUcBqVNEfGHdoHzI9CAtQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iMUcBaVNEfGHdoHzI9CAtQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_nn7JEKVNEfGHdoHzI9CAtQ">
            <expressions xmi:type="expression:ListExpression" xmi:id="_n7zHUKVNEfGHdoHzI9CAtQ">
              <expressions xmi:type="expression:Expression" xmi:id="_n7zHUaVNEfGHdoHzI9CAtQ" content=""/>
              <expressions xmi:type="expression:Expression" xmi:id="_n7zHUqVNEfGHdoHzI9CAtQ"/>
            </expressions>
          </correlation>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_SErHRKVGEfGHdoHzI9CAtQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_SErHRaVGEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_SErHRqVGEfGHdoHzI9CAtQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_SErHR6VGEfGHdoHzI9CAtQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SErHSKVGEfGHdoHzI9CAtQ" target="_9ggsUKVVEfGXn7QjRZTm_Q" source="_SErHM6VGEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SErHSaVGEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_SErHSqVGEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dxPNQKVMEfGHdoHzI9CAtQ" target="_o9jUsKVMEfGHdoHzI9CAtQ" source="_9ggsUKVVEfGXn7QjRZTm_Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dxPNQaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dxPNQqVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iLwQwKVMEfGHdoHzI9CAtQ" target="_iLo8AKVMEfGHdoHzI9CAtQ" source="_o9jUsKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iLwQwaVMEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_iLwQwqVMEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IX-ewKVOEfGHdoHzI9CAtQ" target="_GEL3MKVOEfGHdoHzI9CAtQ" source="_iLo8AKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IX-ewaVOEfGHdoHzI9CAtQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_IX-ewqVOEfGHdoHzI9CAtQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_p0m3gKVXEfGXn7QjRZTm_Q" target="_s-G_EKVXEfGXn7QjRZTm_Q" source="_iLo8AKVMEfGHdoHzI9CAtQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_p0m3gaVXEfGXn7QjRZTm_Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_p0m3gqVXEfGXn7QjRZTm_Q" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tk-KwKVXEfGXn7QjRZTm_Q" target="_m_BWAKVNEfGHdoHzI9CAtQ" source="_s-G_EKVXEfGXn7QjRZTm_Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tk-KwaVXEfGXn7QjRZTm_Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_tk-KwqVXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1SDyQKVXEfGXn7QjRZTm_Q" target="_w37KQKVMEfGHdoHzI9CAtQ" source="_s-G_EKVXEfGXn7QjRZTm_Q">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1SDyQaVXEfGXn7QjRZTm_Q"/>
        <condition xmi:type="expression:Expression" xmi:id="_1SDyQqVXEfGXn7QjRZTm_Q" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_SErHS6VGEfGHdoHzI9CAtQ" documentation="This is an example of actor that is mapped to any ACME users" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_6iL6AKVVEfGXn7QjRZTm_Q" name="Empleado"/>
      <contract xmi:type="process:Contract" xmi:id="_SErHTKVGEfGHdoHzI9CAtQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHTaVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHTqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHT6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHUKVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHUaVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHUqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHU6VGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHVKVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHVaVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHVqVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHV6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHWKVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_SErHWaVGEfGHdoHzI9CAtQ">
        <name xmi:type="expression:Expression" xmi:id="_SErHWqVGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_SErHW6VGEfGHdoHzI9CAtQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_SErHXKVGEfGHdoHzI9CAtQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_SErHXaVGEfGHdoHzI9CAtQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_SErHXqVGEfGHdoHzI9CAtQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_SErHX6VGEfGHdoHzI9CAtQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_SErHYKVGEfGHdoHzI9CAtQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_SErHYaVGEfGHdoHzI9CAtQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_SErHYqVGEfGHdoHzI9CAtQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_SErHY6VGEfGHdoHzI9CAtQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_SErHZKVGEfGHdoHzI9CAtQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_SErHZaVGEfGHdoHzI9CAtQ" type="Process" element="_SErHMKVGEfGHdoHzI9CAtQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_SErHZqVGEfGHdoHzI9CAtQ" type="2007" element="_SErHMaVGEfGHdoHzI9CAtQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHZ6VGEfGHdoHzI9CAtQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHaKVGEfGHdoHzI9CAtQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_SErHaaVGEfGHdoHzI9CAtQ" type="3007" element="_SErHMqVGEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_SErHaqVGEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_SErHa6VGEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_SErHb6VGEfGHdoHzI9CAtQ" type="3002" element="_SErHM6VGEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_SErHcKVGEfGHdoHzI9CAtQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_SErHcaVGEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHcqVGEfGHdoHzI9CAtQ" x="60" y="68"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iLvpsKVMEfGHdoHzI9CAtQ" type="3009" element="_iLo8AKVMEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iLvpsqVMEfGHdoHzI9CAtQ" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iLvps6VMEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iLvpsaVMEfGHdoHzI9CAtQ" x="441" y="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_o9j7x6VMEfGHdoHzI9CAtQ" type="3005" element="_o9jUsKVMEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_o9ki0KVMEfGHdoHzI9CAtQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_o9j7yKVMEfGHdoHzI9CAtQ" x="272" y="64" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w38YYKVMEfGHdoHzI9CAtQ" type="3003" element="_w37KQKVMEfGHdoHzI9CAtQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_w38YYqVMEfGHdoHzI9CAtQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_w38_cKVMEfGHdoHzI9CAtQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w38YYaVMEfGHdoHzI9CAtQ" x="676" y="80"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9gihgKVVEfGXn7QjRZTm_Q" type="3005" element="_9ggsUKVVEfGXn7QjRZTm_Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9gjIkKVVEfGXn7QjRZTm_Q" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9gihgaVVEfGXn7QjRZTm_Q" x="137" y="61" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_s-HmJKVXEfGXn7QjRZTm_Q" type="3025" element="_s-G_EKVXEfGXn7QjRZTm_Q" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_s-HmJqVXEfGXn7QjRZTm_Q" type="5011"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_s-HmJaVXEfGXn7QjRZTm_Q" x="499" y="65" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_SErHc6VGEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_SErHdKVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_SErHdaVGEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_SErHdqVGEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHd6VGEfGHdoHzI9CAtQ" x="48" y="10" width="777" height="250"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_e7pVcKVNEfGHdoHzI9CAtQ" type="3007" element="_e7oHUKVNEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_e7pVdaVNEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_e7pVdqVNEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_m_B9FqVNEfGHdoHzI9CAtQ" type="3026" element="_m_BWAKVNEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_m_B9GKVNEfGHdoHzI9CAtQ" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m_B9F6VNEfGHdoHzI9CAtQ" x="498" y="20" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_e7pVcaVNEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_e7pVcqVNEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_e7pVc6VNEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_e7pVd6VNEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e7pVdKVNEfGHdoHzI9CAtQ" x="113" y="176"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_CuDo4KVOEfGHdoHzI9CAtQ" type="3007" element="_CuCawKVOEfGHdoHzI9CAtQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_CuDo5aVOEfGHdoHzI9CAtQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_CuDo5qVOEfGHdoHzI9CAtQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_GEL3OaVOEfGHdoHzI9CAtQ" type="3027" element="_GEL3MKVOEfGHdoHzI9CAtQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_GEMeQKVOEfGHdoHzI9CAtQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GEL3OqVOEfGHdoHzI9CAtQ" x="384" y="46" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_CuDo4aVOEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_CuDo4qVOEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_CuDo46VOEfGHdoHzI9CAtQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_CuDo56VOEfGHdoHzI9CAtQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CuDo5KVOEfGHdoHzI9CAtQ" x="48" y="10" width="777" height="156"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_SErHeKVGEfGHdoHzI9CAtQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_SErHeaVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_SErHeqVGEfGHdoHzI9CAtQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_SErHe6VGEfGHdoHzI9CAtQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SErHfKVGEfGHdoHzI9CAtQ" width="800" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_SErHfaVGEfGHdoHzI9CAtQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_SErHfqVGEfGHdoHzI9CAtQ" type="4001" element="_SErHSKVGEfGHdoHzI9CAtQ" source="_SErHb6VGEfGHdoHzI9CAtQ" target="_9gihgKVVEfGXn7QjRZTm_Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SErHf6VGEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_SErHgKVGEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_SErHgaVGEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SErHgqVGEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dxP0UKVMEfGHdoHzI9CAtQ" type="4001" element="_dxPNQKVMEfGHdoHzI9CAtQ" source="_9gihgKVVEfGXn7QjRZTm_Q" target="_o9j7x6VMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dxP0U6VMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dxP0VKVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dxP0UaVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dxP0UqVMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iLw30KVMEfGHdoHzI9CAtQ" type="4001" element="_iLwQwKVMEfGHdoHzI9CAtQ" source="_o9j7x6VMEfGHdoHzI9CAtQ" target="_iLvpsKVMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iLw306VMEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iLw31KVMEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iLw30aVMEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iLw30qVMEfGHdoHzI9CAtQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IX_F0KVOEfGHdoHzI9CAtQ" type="4001" element="_IX-ewKVOEfGHdoHzI9CAtQ" source="_iLvpsKVMEfGHdoHzI9CAtQ" target="_GEL3OaVOEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IX_F06VOEfGHdoHzI9CAtQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IX_s4KVOEfGHdoHzI9CAtQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IX_F0aVOEfGHdoHzI9CAtQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IX_F0qVOEfGHdoHzI9CAtQ" points="[-2, -1, 44, 149]$[-2, -121, 44, 29]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IYBiEKVOEfGHdoHzI9CAtQ" id="(0.5348837209302325,0.023255813953488372)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_IYBiEaVOEfGHdoHzI9CAtQ" id="(0.08,0.52)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_p0m3g6VXEfGXn7QjRZTm_Q" type="4001" element="_p0m3gKVXEfGXn7QjRZTm_Q" source="_iLvpsKVMEfGHdoHzI9CAtQ" target="_s-HmJKVXEfGXn7QjRZTm_Q" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_p0nekKVXEfGXn7QjRZTm_Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_p0nekaVXEfGXn7QjRZTm_Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_p0m3hKVXEfGXn7QjRZTm_Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_p0m3haVXEfGXn7QjRZTm_Q" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tk-x0KVXEfGXn7QjRZTm_Q" type="4001" element="_tk-KwKVXEfGXn7QjRZTm_Q" source="_s-HmJKVXEfGXn7QjRZTm_Q" target="_m_B9FqVNEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tk_Y4KVXEfGXn7QjRZTm_Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tk_Y4aVXEfGXn7QjRZTm_Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tk-x0aVXEfGXn7QjRZTm_Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tk-x0qVXEfGXn7QjRZTm_Q" points="[-13, 35, 51, -143]$[-65, 176, -1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tlB1IKVXEfGXn7QjRZTm_Q" id="(0.48333333333333334,0.95)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_tlB1IaVXEfGXn7QjRZTm_Q" id="(0.4666666666666667,0.03333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1SFAYKVXEfGXn7QjRZTm_Q" type="4001" element="_1SDyQKVXEfGXn7QjRZTm_Q" source="_s-HmJKVXEfGXn7QjRZTm_Q" target="_w38YYKVMEfGHdoHzI9CAtQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1SFAY6VXEfGXn7QjRZTm_Q" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1SFAZKVXEfGXn7QjRZTm_Q" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1SFAYaVXEfGXn7QjRZTm_Q" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1SFAYqVXEfGXn7QjRZTm_Q" points="[0, 2, -72, -3]$[66, -10, -6, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1SHcoKVXEfGXn7QjRZTm_Q" id="(1.0,0.4166666666666667)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
