<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:definition="http://www.bonitasoft.org/ns/connector/definition/6.1" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_kCYrUKWFEfGQPrtA8y4eZQ" name="etapa4-6" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_kCZSYKWFEfGQPrtA8y4eZQ" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_kCZSYaWFEfGQPrtA8y4eZQ" name="Sistema" actor="_kCZSeqWFEfGQPrtA8y4eZQ">
        <elements xmi:type="process:StartTimerEvent" xmi:id="_L7w-sKWHEfGQPrtA8y4eZQ" documentation="Va a ser reemplazado por un evento intermedio de temporizador" name="Viene de etapa 3 (Temporizador)" outgoing="_i7rQAKWHEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L713MaWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L713MKWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L713MqWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_fkHeUKWHEfGQPrtA8y4eZQ" name="Obtener ofertas (GET local)" outgoing="_rK238KWHEfGQPrtA8y4eZQ" incoming="_i7rQAKWHEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_fkIFYaWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_fkIFYKWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_fkIFYqWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <data xmi:type="process:Data" xmi:id="_wrFUYKWJEfGQPrtA8y4eZQ" documentation="Listado de ofertas" name="ofertas" dataType="_kCZSkKWFEfGQPrtA8y4eZQ">
            <defaultValue xmi:type="expression:Expression" xmi:id="_wrFUYaWJEfGQPrtA8y4eZQ" content=""/>
          </data>
          <connectors xmi:type="process:Connector" xmi:id="_w9c2wKWJEfGQPrtA8y4eZQ" name="obtenerOfertas" definitionId="rest-get" event="ON_ENTER" definitionVersion="1.4.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_w9c2waWJEfGQPrtA8y4eZQ" definitionId="rest-get" version="1.4.1" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2wqWJEfGQPrtA8y4eZQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2w6WJEfGQPrtA8y4eZQ" name="http://localhost/api/obtenerOfertas" content="http://localhost/api/obtenerOfertas" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2xKWJEfGQPrtA8y4eZQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_w9c2xaWJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2xqWJEfGQPrtA8y4eZQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_w9c2x6WJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2yKWJEfGQPrtA8y4eZQ" key="add_bonita_context_headers">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2yaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2yqWJEfGQPrtA8y4eZQ" key="bonita_activity_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2y6WJEfGQPrtA8y4eZQ" name="X-Bonita-Activity-Instance-Id" content="X-Bonita-Activity-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2zKWJEfGQPrtA8y4eZQ" key="bonita_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2zaWJEfGQPrtA8y4eZQ" name="X-Bonita-Process-Instance-Id" content="X-Bonita-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2zqWJEfGQPrtA8y4eZQ" key="bonita_root_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2z6WJEfGQPrtA8y4eZQ" name="X-Bonita-Root-Process-Instance-Id" content="X-Bonita-Root-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c20KWJEfGQPrtA8y4eZQ" key="bonita_process_definition_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_w9c20aWJEfGQPrtA8y4eZQ" name="X-Bonita-Process-Definition-Id" content="X-Bonita-Process-Definition-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c20qWJEfGQPrtA8y4eZQ" key="bonita_task_assignee_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_w9c206WJEfGQPrtA8y4eZQ" name="X-Bonita-Task-Assignee-Id" content="X-Bonita-Task-Assignee-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c21KWJEfGQPrtA8y4eZQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_w9c21aWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c21qWJEfGQPrtA8y4eZQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_w9c216WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c22KWJEfGQPrtA8y4eZQ" key="fail_on_http_4xx">
                <expression xmi:type="expression:Expression" xmi:id="_w9c22aWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c22qWJEfGQPrtA8y4eZQ" key="fail_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_w9c226WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c23KWJEfGQPrtA8y4eZQ" key="failure_exception_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_w9c23aWJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c23qWJEfGQPrtA8y4eZQ" key="retry_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_w9c236WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c24KWJEfGQPrtA8y4eZQ" key="retry_additional_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_w9c24aWJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c24qWJEfGQPrtA8y4eZQ" key="max_body_content_printed">
                <expression xmi:type="expression:Expression" xmi:id="_w9c246WJEfGQPrtA8y4eZQ" name="1000" content="1000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c25KWJEfGQPrtA8y4eZQ" key="sensitive_headers_printed">
                <expression xmi:type="expression:Expression" xmi:id="_w9c25aWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c25qWJEfGQPrtA8y4eZQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_w9c256WJEfGQPrtA8y4eZQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c26KWJEfGQPrtA8y4eZQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_w9c26aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c26qWJEfGQPrtA8y4eZQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_w9c266WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c27KWJEfGQPrtA8y4eZQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_w9c27aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c27qWJEfGQPrtA8y4eZQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_w9c276WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c28KWJEfGQPrtA8y4eZQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_w9c28aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c28qWJEfGQPrtA8y4eZQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_w9c286WJEfGQPrtA8y4eZQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c29KWJEfGQPrtA8y4eZQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_w9c29aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c29qWJEfGQPrtA8y4eZQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_w9c296WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2-KWJEfGQPrtA8y4eZQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2-aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2-qWJEfGQPrtA8y4eZQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2-6WJEfGQPrtA8y4eZQ" name="-1" content="-1" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2_KWJEfGQPrtA8y4eZQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2_aWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c2_qWJEfGQPrtA8y4eZQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_w9c2_6WJEfGQPrtA8y4eZQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3AKWJEfGQPrtA8y4eZQ" key="oauth2_token_endpoint">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3AaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3AqWJEfGQPrtA8y4eZQ" key="oauth2_client_id">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3A6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3BKWJEfGQPrtA8y4eZQ" key="oauth2_client_secret">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3BaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3BqWJEfGQPrtA8y4eZQ" key="oauth2_scope">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3B6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3CKWJEfGQPrtA8y4eZQ" key="oauth2_audience">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3CaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3CqWJEfGQPrtA8y4eZQ" key="oauth2_token">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3C6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3DKWJEfGQPrtA8y4eZQ" key="oauth2_code">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3DaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3DqWJEfGQPrtA8y4eZQ" key="oauth2_code_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3D6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3EKWJEfGQPrtA8y4eZQ" key="oauth2_redirect_uri">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3EaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3EqWJEfGQPrtA8y4eZQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3E6WJEfGQPrtA8y4eZQ" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3FKWJEfGQPrtA8y4eZQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3FaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3FqWJEfGQPrtA8y4eZQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3F6WJEfGQPrtA8y4eZQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3GKWJEfGQPrtA8y4eZQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3GaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3GqWJEfGQPrtA8y4eZQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3G6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3HKWJEfGQPrtA8y4eZQ" key="automatic_proxy_resolution">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3HaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3HqWJEfGQPrtA8y4eZQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3H6WJEfGQPrtA8y4eZQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3IKWJEfGQPrtA8y4eZQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3IaWJEfGQPrtA8y4eZQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_w9c3IqWJEfGQPrtA8y4eZQ" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_w9c3I6WJEfGQPrtA8y4eZQ" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_w9c3JKWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9c3JaWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9c3JqWJEfGQPrtA8y4eZQ" name="" content=""/>
              <operator xmi:type="expression:Operator" xmi:id="_w9c3J6WJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_w9c3KKWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9c3KaWJEfGQPrtA8y4eZQ" name="ofertas" content="ofertas" type="TYPE_VARIABLE">
                <referencedElements xmi:type="process:Data" xmi:id="_w9c3KqWJEfGQPrtA8y4eZQ" documentation="Listado de ofertas" name="ofertas" dataType="_kCZSkKWFEfGQPrtA8y4eZQ"/>
              </leftOperand>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9c3K6WJEfGQPrtA8y4eZQ" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_w9c3LKWJEfGQPrtA8y4eZQ" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_w9c3LaWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_w9dd0KWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9dd0aWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9dd0qWJEfGQPrtA8y4eZQ" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_w9dd06WJEfGQPrtA8y4eZQ" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_w9dd1KWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_w9dd1aWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9dd1qWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9dd16WJEfGQPrtA8y4eZQ" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_w9dd2KWJEfGQPrtA8y4eZQ" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_w9dd2aWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_w9dd2qWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9dd26WJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9dd3KWJEfGQPrtA8y4eZQ" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_w9dd3aWJEfGQPrtA8y4eZQ" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_w9dd3qWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_w9dd36WJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_w9dd4KWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_w9dd4aWJEfGQPrtA8y4eZQ" content=""/>
              <operator xmi:type="expression:Operator" xmi:id="_w9dd4qWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_fkIFY6WHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_fkIFZKWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_fkIFZaWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_fkIFZ6WHEfGQPrtA8y4eZQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_fkIFZqWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ney14KWHEfGQPrtA8y4eZQ" name="Validar en el Sistema Nacional (POST Cloud)" outgoing="_79J7AKWIEfGQPrtA8y4eZQ" incoming="_rK238KWHEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ney14qWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ney14aWHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ney146WHEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_-_WEMKWJEfGQPrtA8y4eZQ" name="validarOfertas" definitionId="rest-post" event="ON_ENTER" definitionVersion="1.5.1">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-_WEMaWJEfGQPrtA8y4eZQ" definitionId="rest-post" version="1.5.1" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEMqWJEfGQPrtA8y4eZQ" key="url">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEM6WJEfGQPrtA8y4eZQ" name="http://sistemaNacional/api/validarOfertas" content="http://sistemaNacional/api/validarOfertas" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WENKWJEfGQPrtA8y4eZQ" key="contentType">
                <expression xmi:type="expression:Expression" xmi:id="_-_WENaWJEfGQPrtA8y4eZQ" name="application/json" content="application/json" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WENqWJEfGQPrtA8y4eZQ" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEN6WJEfGQPrtA8y4eZQ" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEOKWJEfGQPrtA8y4eZQ" key="urlCookies">
                <expression xmi:type="expression:TableExpression" xmi:id="_-_WEOaWJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEOqWJEfGQPrtA8y4eZQ" key="urlHeaders">
                <expression xmi:type="expression:TableExpression" xmi:id="_-_WEO6WJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEPKWJEfGQPrtA8y4eZQ" key="add_bonita_context_headers">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEPaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEPqWJEfGQPrtA8y4eZQ" key="bonita_activity_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEP6WJEfGQPrtA8y4eZQ" name="X-Bonita-Activity-Instance-Id" content="X-Bonita-Activity-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEQKWJEfGQPrtA8y4eZQ" key="bonita_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEQaWJEfGQPrtA8y4eZQ" name="X-Bonita-Process-Instance-Id" content="X-Bonita-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEQqWJEfGQPrtA8y4eZQ" key="bonita_root_process_instance_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEQ6WJEfGQPrtA8y4eZQ" name="X-Bonita-Root-Process-Instance-Id" content="X-Bonita-Root-Process-Instance-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WERKWJEfGQPrtA8y4eZQ" key="bonita_process_definition_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_-_WERaWJEfGQPrtA8y4eZQ" name="X-Bonita-Process-Definition-Id" content="X-Bonita-Process-Definition-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WERqWJEfGQPrtA8y4eZQ" key="bonita_task_assignee_id_header">
                <expression xmi:type="expression:Expression" xmi:id="_-_WER6WJEfGQPrtA8y4eZQ" name="X-Bonita-Task-Assignee-Id" content="X-Bonita-Task-Assignee-Id" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WESKWJEfGQPrtA8y4eZQ" key="body">
                <expression xmi:type="expression:Expression" xmi:id="_-_WESaWJEfGQPrtA8y4eZQ" name="body()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WESqWJEfGQPrtA8y4eZQ" key="do_not_follow_redirect">
                <expression xmi:type="expression:Expression" xmi:id="_-_WES6WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WETKWJEfGQPrtA8y4eZQ" key="ignore_body">
                <expression xmi:type="expression:Expression" xmi:id="_-_WETaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WETqWJEfGQPrtA8y4eZQ" key="fail_on_http_4xx">
                <expression xmi:type="expression:Expression" xmi:id="_-_WET6WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEUKWJEfGQPrtA8y4eZQ" key="fail_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEUaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEUqWJEfGQPrtA8y4eZQ" key="failure_exception_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_-_WEU6WJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEVKWJEfGQPrtA8y4eZQ" key="retry_on_http_5xx">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEVaWJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEVqWJEfGQPrtA8y4eZQ" key="retry_additional_codes">
                <expression xmi:type="expression:TableExpression" xmi:id="_-_WEV6WJEfGQPrtA8y4eZQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEWKWJEfGQPrtA8y4eZQ" key="max_body_content_printed">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEWaWJEfGQPrtA8y4eZQ" name="1000" content="1000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEWqWJEfGQPrtA8y4eZQ" key="sensitive_headers_printed">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEW6WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEXKWJEfGQPrtA8y4eZQ" key="TLS">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEXaWJEfGQPrtA8y4eZQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEXqWJEfGQPrtA8y4eZQ" key="hostname_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEX6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEYKWJEfGQPrtA8y4eZQ" key="trust_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEYaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEYqWJEfGQPrtA8y4eZQ" key="trust_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEY6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEZKWJEfGQPrtA8y4eZQ" key="key_store_file">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEZaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEZqWJEfGQPrtA8y4eZQ" key="key_store_password">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEZ6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEaKWJEfGQPrtA8y4eZQ" key="auth_type">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEaaWJEfGQPrtA8y4eZQ" name="NONE" content="NONE" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEaqWJEfGQPrtA8y4eZQ" key="auth_username">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEa6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEbKWJEfGQPrtA8y4eZQ" key="auth_password">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEbaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEbqWJEfGQPrtA8y4eZQ" key="auth_host">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEb6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEcKWJEfGQPrtA8y4eZQ" key="auth_port">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEcaWJEfGQPrtA8y4eZQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEcqWJEfGQPrtA8y4eZQ" key="auth_realm">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEc6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEdKWJEfGQPrtA8y4eZQ" key="auth_preemptive">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEdaWJEfGQPrtA8y4eZQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEdqWJEfGQPrtA8y4eZQ" key="oauth2_token_endpoint">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEd6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEeKWJEfGQPrtA8y4eZQ" key="oauth2_client_id">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEeaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEeqWJEfGQPrtA8y4eZQ" key="oauth2_client_secret">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEe6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEfKWJEfGQPrtA8y4eZQ" key="oauth2_scope">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEfaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEfqWJEfGQPrtA8y4eZQ" key="oauth2_audience">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEf6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEgKWJEfGQPrtA8y4eZQ" key="oauth2_token">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEgaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEgqWJEfGQPrtA8y4eZQ" key="oauth2_code">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEg6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEhKWJEfGQPrtA8y4eZQ" key="oauth2_code_verifier">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEhaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEhqWJEfGQPrtA8y4eZQ" key="oauth2_redirect_uri">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEh6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEiKWJEfGQPrtA8y4eZQ" key="proxy_protocol">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEiaWJEfGQPrtA8y4eZQ" name="HTTP" content="HTTP" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEiqWJEfGQPrtA8y4eZQ" key="proxy_host">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEi6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEjKWJEfGQPrtA8y4eZQ" key="proxy_port">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEjaWJEfGQPrtA8y4eZQ" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEjqWJEfGQPrtA8y4eZQ" key="proxy_username">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEj6WJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEkKWJEfGQPrtA8y4eZQ" key="proxy_password">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEkaWJEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEkqWJEfGQPrtA8y4eZQ" key="automatic_proxy_resolution">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEk6WJEfGQPrtA8y4eZQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WElKWJEfGQPrtA8y4eZQ" key="socket_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_-_WElaWJEfGQPrtA8y4eZQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WElqWJEfGQPrtA8y4eZQ" key="connection_timeout_ms">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEl6WJEfGQPrtA8y4eZQ" name="60000" content="60000" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-_WEmKWJEfGQPrtA8y4eZQ" key="trust_strategy">
                <expression xmi:type="expression:Expression" xmi:id="_-_WEmaWJEfGQPrtA8y4eZQ" name="DEFAULT" content="DEFAULT" returnTypeFixed="true"/>
              </parameters>
            </configuration>
            <outputs xmi:type="expression:Operation" xmi:id="_-_WEmqWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_-_WEm6WJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_-_WEnKWJEfGQPrtA8y4eZQ" name="bodyAsString" content="bodyAsString" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_-_WEnaWJEfGQPrtA8y4eZQ" name="bodyAsString" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_-_WEnqWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_-_WEn6WJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_-_WEoKWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_-_WEoaWJEfGQPrtA8y4eZQ" name="bodyAsObject" content="bodyAsObject" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Object">
                <referencedElements xmi:type="definition:Output" xmi:id="_-_WEoqWJEfGQPrtA8y4eZQ" name="bodyAsObject" type="java.lang.Object"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_-_WEo6WJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_-_WEpKWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_-_WEpaWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_-_WEpqWJEfGQPrtA8y4eZQ" name="headers" content="headers" type="CONNECTOR_OUTPUT_TYPE" returnType="java.util.Map">
                <referencedElements xmi:type="definition:Output" xmi:id="_-_WEp6WJEfGQPrtA8y4eZQ" name="headers" type="java.util.Map"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_-_WEqKWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_-_WEqaWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_-_WEqqWJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_-_WEq6WJEfGQPrtA8y4eZQ" name="status_code" content="status_code" type="CONNECTOR_OUTPUT_TYPE" returnType="java.lang.Integer">
                <referencedElements xmi:type="definition:Output" xmi:id="_-_WErKWJEfGQPrtA8y4eZQ" name="status_code" type="java.lang.Integer"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_-_WEraWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
            <outputs xmi:type="expression:Operation" xmi:id="_-_WErqWJEfGQPrtA8y4eZQ">
              <leftOperand xmi:type="expression:Expression" xmi:id="_-_WEr6WJEfGQPrtA8y4eZQ"/>
              <rightOperand xmi:type="expression:Expression" xmi:id="_-_WEsKWJEfGQPrtA8y4eZQ" name="status_message" content="status_message" type="CONNECTOR_OUTPUT_TYPE">
                <referencedElements xmi:type="definition:Output" xmi:id="_-_WEsaWJEfGQPrtA8y4eZQ" name="status_message" type="java.lang.String"/>
              </rightOperand>
              <operator xmi:type="expression:Operator" xmi:id="_-_WEsqWJEfGQPrtA8y4eZQ" type="ASSIGNMENT"/>
            </outputs>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ney15KWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ney15aWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ney15qWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ney16KWHEfGQPrtA8y4eZQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ney156WHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_S-MqMKWIEfGQPrtA8y4eZQ" name="Viene de etapa 5 (Adjudicación)" outgoing="_W6tjEKWIEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_S-NRQaWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_S-NRQKWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_S-NRQqWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_VYeUQKWIEfGQPrtA8y4eZQ" name="Registrar compromiso y bloqueo" outgoing="_dJfZgKWIEfGQPrtA8y4eZQ" incoming="_W6tjEKWIEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_VYeUQqWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_VYeUQaWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_VYeUQ6WIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_VYeURKWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_VYeURaWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_VYeURqWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_VYeUSKWIEfGQPrtA8y4eZQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_VYeUR6WIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_aZUX8KWIEfGQPrtA8y4eZQ" name="Va a etapa 7 (Ejecución y monitoreo)" incoming="_dJfZgKWIEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aZU_AaWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aZU_AKWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aZU_AqWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_6Qou0KWIEfGQPrtA8y4eZQ" name="Va a etapa 5 (adjudicación)" incoming="_79J7AKWIEfGQPrtA8y4eZQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6QpV4aWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6QpV4KWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6QpV4qWIEfGQPrtA8y4eZQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_Sh8mQKY8EfGtH8AM0GyzNg" text="Si cumple, etapa 5 si no, vuelve a la tarea al Centro Coordinador para que evalúe y decida un curso de acción (ej. reabrir la convocatoria, reformular lotes o continuar con cobertura parcial)."/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_KefyoKWLEfGQPrtA8y4eZQ" name="ofertasConsolidadas" dataType="_kCZSkKWFEfGQPrtA8y4eZQ">
        <defaultValue xmi:type="expression:Expression" xmi:id="_KefyoaWLEfGQPrtA8y4eZQ" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_kCZSc6WFEfGQPrtA8y4eZQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_kCZSdKWFEfGQPrtA8y4eZQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_kCZSdaWFEfGQPrtA8y4eZQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_kCZSdqWFEfGQPrtA8y4eZQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i7rQAKWHEfGQPrtA8y4eZQ" target="_fkHeUKWHEfGQPrtA8y4eZQ" source="_L7w-sKWHEfGQPrtA8y4eZQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i7rQAaWHEfGQPrtA8y4eZQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_i7rQAqWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rK238KWHEfGQPrtA8y4eZQ" target="_ney14KWHEfGQPrtA8y4eZQ" source="_fkHeUKWHEfGQPrtA8y4eZQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rK3fAKWHEfGQPrtA8y4eZQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_rK3fAaWHEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_W6tjEKWIEfGQPrtA8y4eZQ" target="_VYeUQKWIEfGQPrtA8y4eZQ" source="_S-MqMKWIEfGQPrtA8y4eZQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_W6uKIKWIEfGQPrtA8y4eZQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_W6uKIaWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dJfZgKWIEfGQPrtA8y4eZQ" target="_aZUX8KWIEfGQPrtA8y4eZQ" source="_VYeUQKWIEfGQPrtA8y4eZQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dJgAkKWIEfGQPrtA8y4eZQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_dJgAkaWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_79J7AKWIEfGQPrtA8y4eZQ" target="_6Qou0KWIEfGQPrtA8y4eZQ" source="_ney14KWHEfGQPrtA8y4eZQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_79J7AaWIEfGQPrtA8y4eZQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_79J7AqWIEfGQPrtA8y4eZQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_kCZSeqWFEfGQPrtA8y4eZQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_kCZSe6WFEfGQPrtA8y4eZQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kCZSfKWFEfGQPrtA8y4eZQ">
        <name xmi:type="expression:Expression" xmi:id="_kCZSfaWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kCZSfqWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kCZSf6WFEfGQPrtA8y4eZQ">
        <name xmi:type="expression:Expression" xmi:id="_kCZSgKWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kCZSgaWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kCZSgqWFEfGQPrtA8y4eZQ">
        <name xmi:type="expression:Expression" xmi:id="_kCZSg6WFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kCZShKWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kCZShaWFEfGQPrtA8y4eZQ">
        <name xmi:type="expression:Expression" xmi:id="_kCZShqWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kCZSh6WFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_kCZSiKWFEfGQPrtA8y4eZQ">
        <name xmi:type="expression:Expression" xmi:id="_kCZSiaWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_kCZSiqWFEfGQPrtA8y4eZQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_kCZSi6WFEfGQPrtA8y4eZQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_kCZSjKWFEfGQPrtA8y4eZQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_kCZSjaWFEfGQPrtA8y4eZQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_kCZSjqWFEfGQPrtA8y4eZQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_kCZSj6WFEfGQPrtA8y4eZQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_kCZSkKWFEfGQPrtA8y4eZQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_kCZSkaWFEfGQPrtA8y4eZQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_kCZSkqWFEfGQPrtA8y4eZQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_kCZSk6WFEfGQPrtA8y4eZQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_kCZSlKWFEfGQPrtA8y4eZQ" type="Process" element="_kCYrUKWFEfGQPrtA8y4eZQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_kCZSlaWFEfGQPrtA8y4eZQ" type="2007" element="_kCZSYKWFEfGQPrtA8y4eZQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_kCZSlqWFEfGQPrtA8y4eZQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_kCZSl6WFEfGQPrtA8y4eZQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_kCZSmKWFEfGQPrtA8y4eZQ" type="3007" element="_kCZSYaWFEfGQPrtA8y4eZQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_kCZSmaWFEfGQPrtA8y4eZQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_kCZSmqWFEfGQPrtA8y4eZQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_L8McgKWHEfGQPrtA8y4eZQ" type="3016" element="_L7w-sKWHEfGQPrtA8y4eZQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_L8NDkKWHEfGQPrtA8y4eZQ" type="5031">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_L8NDkaWHEfGQPrtA8y4eZQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L8McgaWHEfGQPrtA8y4eZQ" x="99" y="141"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_fkJTgKWHEfGQPrtA8y4eZQ" type="3027" element="_fkHeUKWHEfGQPrtA8y4eZQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_fkJTgqWHEfGQPrtA8y4eZQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fkJTgaWHEfGQPrtA8y4eZQ" x="194" y="46" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ne0EAKWHEfGQPrtA8y4eZQ" type="3027" element="_ney14KWHEfGQPrtA8y4eZQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ne0rEKWHEfGQPrtA8y4eZQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ne0EAaWHEfGQPrtA8y4eZQ" x="460" y="51" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_S-N4UKWIEfGQPrtA8y4eZQ" type="3002" element="_S-MqMKWIEfGQPrtA8y4eZQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_S-OfYKWIEfGQPrtA8y4eZQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_S-OfYaWIEfGQPrtA8y4eZQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_S-N4UaWIEfGQPrtA8y4eZQ" x="100" y="372"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_VYe7UKWIEfGQPrtA8y4eZQ" type="3027" element="_VYeUQKWIEfGQPrtA8y4eZQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_VYfiYKWIEfGQPrtA8y4eZQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VYe7UaWIEfGQPrtA8y4eZQ" x="251" y="293" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aZWNIKWIEfGQPrtA8y4eZQ" type="3003" element="_aZUX8KWIEfGQPrtA8y4eZQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aZWNIqWIEfGQPrtA8y4eZQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aZWNI6WIEfGQPrtA8y4eZQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aZWNIaWIEfGQPrtA8y4eZQ" x="604" y="355"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_6Qp88KWIEfGQPrtA8y4eZQ" type="3003" element="_6Qou0KWIEfGQPrtA8y4eZQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_6Qp88qWIEfGQPrtA8y4eZQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_6Qp886WIEfGQPrtA8y4eZQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6Qp88aWIEfGQPrtA8y4eZQ" x="669" y="141"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_SiVAwKY8EfGtH8AM0GyzNg" type="3015" element="_Sh8mQKY8EfGtH8AM0GyzNg">
              <children xmi:type="notation:DecorationNode" xmi:id="_SiWO4KY8EfGtH8AM0GyzNg" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_SiVn0KY8EfGtH8AM0GyzNg"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_SiVn0aY8EfGtH8AM0GyzNg" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_SiVn0qY8EfGtH8AM0GyzNg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_SiVn06Y8EfGtH8AM0GyzNg" x="441" y="160" width="153" height="58"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_kCZSoqWFEfGQPrtA8y4eZQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_kCZSo6WFEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_kCZSpKWFEfGQPrtA8y4eZQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_kCZSpaWFEfGQPrtA8y4eZQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCZSpqWFEfGQPrtA8y4eZQ" x="48" y="10" width="777" height="550"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_kCZSp6WFEfGQPrtA8y4eZQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_kCZSqKWFEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_kCZSqaWFEfGQPrtA8y4eZQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_kCZSqqWFEfGQPrtA8y4eZQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_kCZSq6WFEfGQPrtA8y4eZQ" width="800" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_kCZSrKWFEfGQPrtA8y4eZQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_i7r3EKWHEfGQPrtA8y4eZQ" type="4001" element="_i7rQAKWHEfGQPrtA8y4eZQ" source="_L8McgKWHEfGQPrtA8y4eZQ" target="_fkJTgKWHEfGQPrtA8y4eZQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i7seIKWHEfGQPrtA8y4eZQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i7seIaWHEfGQPrtA8y4eZQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i7r3EaWHEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i7r3EqWHEfGQPrtA8y4eZQ" points="[3, -5, -88, 88]$[72, -94, -19, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i7zy4KWHEfGQPrtA8y4eZQ" id="(0.7666666666666667,0.3333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_i7zy4aWHEfGQPrtA8y4eZQ" id="(0.15833333333333333,0.48333333333333334)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rK4GEKWHEfGQPrtA8y4eZQ" type="4001" element="_rK238KWHEfGQPrtA8y4eZQ" source="_fkJTgKWHEfGQPrtA8y4eZQ" target="_ne0EAKWHEfGQPrtA8y4eZQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rK4tIKWHEfGQPrtA8y4eZQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rK4tIaWHEfGQPrtA8y4eZQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rK4GEaWHEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rK4GEqWHEfGQPrtA8y4eZQ" points="[0, 0, -146, -17]$[146, 17, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rK6iUKWHEfGQPrtA8y4eZQ" id="(1.0,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rK6iUaWHEfGQPrtA8y4eZQ" id="(0.0,0.5714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_W6uxMKWIEfGQPrtA8y4eZQ" type="4001" element="_W6tjEKWIEfGQPrtA8y4eZQ" source="_S-N4UKWIEfGQPrtA8y4eZQ" target="_VYe7UKWIEfGQPrtA8y4eZQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_W6uxM6WIEfGQPrtA8y4eZQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_W6uxNKWIEfGQPrtA8y4eZQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_W6uxMaWIEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_W6uxMqWIEfGQPrtA8y4eZQ" points="[-2, -19, -167, 59]$[159, -78, -6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W6xNcKWIEfGQPrtA8y4eZQ" id="(1.0,0.9666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_W6xNcaWIEfGQPrtA8y4eZQ" id="(0.05,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dJgnoKWIEfGQPrtA8y4eZQ" type="4001" element="_dJfZgKWIEfGQPrtA8y4eZQ" source="_VYe7UKWIEfGQPrtA8y4eZQ" target="_aZWNIKWIEfGQPrtA8y4eZQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dJgno6WIEfGQPrtA8y4eZQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dJgnpKWIEfGQPrtA8y4eZQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dJgnoaWIEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dJgnoqWIEfGQPrtA8y4eZQ" points="[0, 0, -248, -53]$[243, 67, -5, 14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_dJic0KWIEfGQPrtA8y4eZQ" id="(1.0,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_79KiEKWIEfGQPrtA8y4eZQ" type="4001" element="_79J7AKWIEfGQPrtA8y4eZQ" source="_ne0EAKWHEfGQPrtA8y4eZQ" target="_6Qp88KWIEfGQPrtA8y4eZQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_79LJIKWIEfGQPrtA8y4eZQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_79LJIaWIEfGQPrtA8y4eZQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_79KiEaWIEfGQPrtA8y4eZQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_79KiEqWIEfGQPrtA8y4eZQ" points="[0, 0, -84, -80]$[82, 65, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_79MXQKWIEfGQPrtA8y4eZQ" id="(1.0,0.35714285714285715)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
