<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_FVHYcKVTEfG5LfnfHAWAzw" name="MiDiagrama" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_FVHYcaVTEfG5LfnfHAWAzw" name="Pool">
      <elements xmi:type="process:Task" xmi:id="_FVHYd6VTEfG5LfnfHAWAzw" documentation="Tarea de Usuario porque se interactúa con el Centro Coordinador." name="Monitoreo del despliegue" outgoing="_523hkKVUEfG5LfnfHAWAzw" incoming="_FVHYiKVTEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_FVHYeKVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_FVHYeaVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_FVHYeqVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_FVHYe6VTEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_FVHYfKVTEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FVHYfaVTEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_FVHYfqVTEfG5LfnfHAWAzw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_FVHYf6VTEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_FVHYgKVTEfG5LfnfHAWAzw">
          <targetForm xmi:type="expression:Expression" xmi:id="_FVHYgaVTEfG5LfnfHAWAzw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_FVHYgqVTEfG5LfnfHAWAzw"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_FVHYg6VTEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:StartEvent" xmi:id="_FVHYc6VTEfG5LfnfHAWAzw" name="Inicio" outgoing="_FVHYiKVTEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_FVHYdKVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_FVHYdaVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_FVHYdqVTEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:IntermediateCatchSignalEvent" xmi:id="_zP2KQKVUEfG5LfnfHAWAzw" documentation="Queda a espera de que alguna ONG del proyecto marque alguna de sus actividades como finalizada." name="ONG finaliza actividad" outgoing="_I8N6oKVWEfG5LfnfHAWAzw" incoming="_523hkKVUEfG5LfnfHAWAzw _PgzB8KVWEfG5LfnfHAWAzw _WgCPgKVXEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_zP2xUaVUEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_zP2xUKVUEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_zP2xUqVUEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_ElDtIKVWEfG5LfnfHAWAzw" name="Esa ONG tiene más actividades pendientes?" outgoing="_PgzB8KVWEfG5LfnfHAWAzw _ot-cEKVWEfG5LfnfHAWAzw" incoming="_I8N6oKVWEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_ElEUMaVWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_ElEUMKVWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_ElEUMqVWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_khRyIKVWEfG5LfnfHAWAzw" documentation="La plataforma se comunica con la API del Cloud para informar de la liberación de los recursos cedidos por la respectiva ONG que se está procesando." name="Informar finalización de ONG al Sistema Centralizado" outgoing="_Po700KVXEfG5LfnfHAWAzw" incoming="_ot-cEKVWEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_khRyIqVWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_khRyIaVWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_khRyI6VWEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_khRyJKVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_khRyJaVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_khRyJqVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_khRyKKVWEfG5LfnfHAWAzw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_khRyJ6VWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_NYteoKVXEfG5LfnfHAWAzw" name="Hay más ONGs con actividades pendientes?" outgoing="_WgCPgKVXEfG5LfnfHAWAzw _jaJVgKVXEfG5LfnfHAWAzw" incoming="_Po700KVXEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_NYteoaVXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_NYteoqVXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_NYteo6VXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_h3xj0KVXEfG5LfnfHAWAzw" documentation="Se da por finalizado el proyecto, luego de que todas las ONGs finalizaron sus actividades." name="Fin Proyecto" incoming="_jaJVgKVXEfG5LfnfHAWAzw">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_h3yK4aVXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_h3yK4KVXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_h3yK4qVXEfG5LfnfHAWAzw" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:TextAnnotation" xmi:id="_qbjqQKY9EfGSU7nkIws_og" text="necesario modelar el envio del mensaje de parte de la ong?"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_FVHYhKVTEfG5LfnfHAWAzw">
        <targetForm xmi:type="expression:Expression" xmi:id="_FVHYhaVTEfG5LfnfHAWAzw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_FVHYhqVTEfG5LfnfHAWAzw">
        <targetForm xmi:type="expression:Expression" xmi:id="_FVHYh6VTEfG5LfnfHAWAzw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FVHYiKVTEfG5LfnfHAWAzw" target="_FVHYd6VTEfG5LfnfHAWAzw" source="_FVHYc6VTEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FVHYiaVTEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_FVHYiqVTEfG5LfnfHAWAzw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_523hkKVUEfG5LfnfHAWAzw" target="_zP2KQKVUEfG5LfnfHAWAzw" source="_FVHYd6VTEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_524IoKVUEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_524IoaVUEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_I8N6oKVWEfG5LfnfHAWAzw" target="_ElDtIKVWEfG5LfnfHAWAzw" source="_zP2KQKVUEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_I8N6oaVWEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_I8N6oqVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PgzB8KVWEfG5LfnfHAWAzw" name="Si" target="_zP2KQKVUEfG5LfnfHAWAzw" source="_ElDtIKVWEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PgzB8aVWEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_PgzB8qVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ot-cEKVWEfG5LfnfHAWAzw" name="No" target="_khRyIKVWEfG5LfnfHAWAzw" source="_ElDtIKVWEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ot-cEaVWEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_ot-cEqVWEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Po700KVXEfG5LfnfHAWAzw" target="_NYteoKVXEfG5LfnfHAWAzw" source="_khRyIKVWEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Po700aVXEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_Po700qVXEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WgCPgKVXEfG5LfnfHAWAzw" name="Si" target="_zP2KQKVUEfG5LfnfHAWAzw" source="_NYteoKVXEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WgC2kKVXEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_WgC2kaVXEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jaJVgKVXEfG5LfnfHAWAzw" name="No" target="_h3xj0KVXEfG5LfnfHAWAzw" source="_NYteoKVXEfG5LfnfHAWAzw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jaJVgaVXEfG5LfnfHAWAzw"/>
        <condition xmi:type="expression:Expression" xmi:id="_jaJVgqVXEfG5LfnfHAWAzw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_FVHYi6VTEfG5LfnfHAWAzw" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_FVHYjKVTEfG5LfnfHAWAzw"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_FVHYjaVTEfG5LfnfHAWAzw">
        <name xmi:type="expression:Expression" xmi:id="_FVHYjqVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_FVHYj6VTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_FVHYkKVTEfG5LfnfHAWAzw">
        <name xmi:type="expression:Expression" xmi:id="_FVHYkaVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_FVHYkqVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_FVHYk6VTEfG5LfnfHAWAzw">
        <name xmi:type="expression:Expression" xmi:id="_FVHYlKVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_FVHYlaVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_FVHYlqVTEfG5LfnfHAWAzw">
        <name xmi:type="expression:Expression" xmi:id="_FVHYl6VTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_FVHYmKVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_FVHYmaVTEfG5LfnfHAWAzw">
        <name xmi:type="expression:Expression" xmi:id="_FVHYmqVTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_FVHYm6VTEfG5LfnfHAWAzw" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_FVHYnKVTEfG5LfnfHAWAzw" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_FVHYnaVTEfG5LfnfHAWAzw" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_FVHYnqVTEfG5LfnfHAWAzw" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_FVHYn6VTEfG5LfnfHAWAzw" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_FVHYoKVTEfG5LfnfHAWAzw" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_FVHYoaVTEfG5LfnfHAWAzw" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_FVHYoqVTEfG5LfnfHAWAzw" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_FVHYo6VTEfG5LfnfHAWAzw" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_FVHYpKVTEfG5LfnfHAWAzw" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_FVH_gKVTEfG5LfnfHAWAzw" type="Process" element="_FVHYcKVTEfG5LfnfHAWAzw" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_FVH_gaVTEfG5LfnfHAWAzw" type="2007" element="_FVHYcaVTEfG5LfnfHAWAzw">
      <children xmi:type="notation:DecorationNode" xmi:id="_FVH_gqVTEfG5LfnfHAWAzw" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_FVH_g6VTEfG5LfnfHAWAzw" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_FVH_h6VTEfG5LfnfHAWAzw" type="3005" element="_FVHYd6VTEfG5LfnfHAWAzw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_FVH_iKVTEfG5LfnfHAWAzw" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FVH_iaVTEfG5LfnfHAWAzw" x="160" y="60" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_FVH_iqVTEfG5LfnfHAWAzw" type="3002" element="_FVHYc6VTEfG5LfnfHAWAzw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_FVH_i6VTEfG5LfnfHAWAzw" type="5024">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_FVH_jKVTEfG5LfnfHAWAzw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FVH_jaVTEfG5LfnfHAWAzw" x="60" y="68"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_zP4mgKVUEfG5LfnfHAWAzw" type="3021" element="_zP2KQKVUEfG5LfnfHAWAzw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_zP4mgqVUEfG5LfnfHAWAzw" type="5036">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_zP4mg6VUEfG5LfnfHAWAzw" x="-2" y="-44"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zP4mgaVUEfG5LfnfHAWAzw" x="364" y="68"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_ElFiUKVWEfG5LfnfHAWAzw" type="3008" element="_ElDtIKVWEfG5LfnfHAWAzw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_ElFiUqVWEfG5LfnfHAWAzw" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_ElFiU6VWEfG5LfnfHAWAzw" y="-65"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ElFiUaVWEfG5LfnfHAWAzw" x="536" y="61"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_khSZMKVWEfG5LfnfHAWAzw" type="3027" element="_khRyIKVWEfG5LfnfHAWAzw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_khSZMqVWEfG5LfnfHAWAzw" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_khSZMaVWEfG5LfnfHAWAzw" x="749" y="46" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_NYuFsKVXEfG5LfnfHAWAzw" type="3008" element="_NYteoKVXEfG5LfnfHAWAzw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_NYuFsaVXEfG5LfnfHAWAzw" type="5026" element="_NYteoKVXEfG5LfnfHAWAzw">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_NYuFsqVXEfG5LfnfHAWAzw" x="-2" y="8"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NYuFs6VXEfG5LfnfHAWAzw" x="787" y="198"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_h3yx8KVXEfG5LfnfHAWAzw" type="3062" element="_h3xj0KVXEfG5LfnfHAWAzw" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_h3yx8qVXEfG5LfnfHAWAzw" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_h3yx86VXEfG5LfnfHAWAzw" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h3yx8aVXEfG5LfnfHAWAzw" x="954" y="205"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_qcI5EKY9EfGSU7nkIws_og" type="3015" element="_qbjqQKY9EfGSU7nkIws_og">
          <children xmi:type="notation:DecorationNode" xmi:id="_qcJgIKY9EfGSU7nkIws_og" type="5010"/>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_qcI5EaY9EfGSU7nkIws_og"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_qcI5EqY9EfGSU7nkIws_og" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_qcI5E6Y9EfGSU7nkIws_og"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_qcI5FKY9EfGSU7nkIws_og" x="236" y="152"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_FVH_k6VTEfG5LfnfHAWAzw"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_FVH_lKVTEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_FVH_laVTEfG5LfnfHAWAzw"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_FVH_lqVTEfG5LfnfHAWAzw"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FVH_l6VTEfG5LfnfHAWAzw" width="1100" height="277"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_FVH_mKVTEfG5LfnfHAWAzw"/>
    <edges xmi:type="notation:Connector" xmi:id="_FVH_maVTEfG5LfnfHAWAzw" type="4001" element="_FVHYiKVTEfG5LfnfHAWAzw" source="_FVH_iqVTEfG5LfnfHAWAzw" target="_FVH_h6VTEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FVH_mqVTEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FVH_m6VTEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FVH_nKVTEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FVH_naVTEfG5LfnfHAWAzw" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_525WwKVUEfG5LfnfHAWAzw" type="4001" element="_523hkKVUEfG5LfnfHAWAzw" source="_FVH_h6VTEfG5LfnfHAWAzw" target="_zP4mgKVUEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_525Ww6VUEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_52590KVUEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_525WwaVUEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_525WwqVUEfG5LfnfHAWAzw" points="[0, 0, -99, -2]$[97, -13, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_527L8KVUEfG5LfnfHAWAzw" id="(1.0,0.35)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_I8OhsKVWEfG5LfnfHAWAzw" type="4001" element="_I8N6oKVWEfG5LfnfHAWAzw" source="_zP4mgKVUEfG5LfnfHAWAzw" target="_ElFiUKVWEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_I8Ohs6VWEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_I8PIwKVWEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_I8OhsaVWEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_I8OhsqVWEfG5LfnfHAWAzw" points="[-1, -10, -146, 0]$[142, -10, -3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_I8Pv0KVWEfG5LfnfHAWAzw" id="(1.0,0.8)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_I8Pv0aVWEfG5LfnfHAWAzw" id="(0.06976744186046512,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Pg0QEKVWEfG5LfnfHAWAzw" type="4001" element="_PgzB8KVWEfG5LfnfHAWAzw" source="_ElFiUKVWEfG5LfnfHAWAzw" target="_zP4mgKVUEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pg03IKVWEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Pg03IaVWEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Pg0QEaVWEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Pg0QEqVWEfG5LfnfHAWAzw" points="[-22, 17, 184, 12]$[-22, 92, 184, 87]$[-200, 92, 6, 87]$[-200, 10, 6, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Pg2FQKVWEfG5LfnfHAWAzw" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Pg2sUKVWEfG5LfnfHAWAzw" id="(0.3,0.8)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ouINEKVWEfG5LfnfHAWAzw" type="4001" element="_ot-cEKVWEfG5LfnfHAWAzw" source="_ElFiUKVWEfG5LfnfHAWAzw" target="_khSZMKVWEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ouI0IKVWEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ouI0IaVWEfG5LfnfHAWAzw" y="16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ouINEaVWEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ouINEqVWEfG5LfnfHAWAzw" points="[-3, -10, -175, -6]$[170, -10, -2, -6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ouKCQKVWEfG5LfnfHAWAzw" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ouKCQaVWEfG5LfnfHAWAzw" id="(0.02,0.58)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Po8b4KVXEfG5LfnfHAWAzw" type="4001" element="_Po700KVXEfG5LfnfHAWAzw" source="_khSZMKVWEfG5LfnfHAWAzw" target="_NYuFsKVXEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Po9C8KVXEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Po9C8aVXEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Po8b4aVXEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Po8b4qVXEfG5LfnfHAWAzw" points="[-81, 35, 3, -82]$[-81, 117, 3, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Po9qAKVXEfG5LfnfHAWAzw" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Po9qAaVXEfG5LfnfHAWAzw" id="(0.4186046511627907,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WgC2kqVXEfG5LfnfHAWAzw" type="4001" element="_WgCPgKVXEfG5LfnfHAWAzw" source="_NYuFsKVXEfG5LfnfHAWAzw" target="_zP4mgKVUEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WgDdoKVXEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WgDdoaVXEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WgC2k6VXEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WgC2lKVXEfG5LfnfHAWAzw" points="[-43, -11, 418, 125]$[-452, -11, 9, 125]$[-452, -133, 9, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WgErwKVXEfG5LfnfHAWAzw" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WgErwaVXEfG5LfnfHAWAzw" id="(0.16666666666666666,0.8666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jaO1EKVXEfG5LfnfHAWAzw" type="4001" element="_jaJVgKVXEfG5LfnfHAWAzw" source="_NYuFsKVXEfG5LfnfHAWAzw" target="_h3yx8KVXEfG5LfnfHAWAzw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jaO1E6VXEfG5LfnfHAWAzw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jaO1FKVXEfG5LfnfHAWAzw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jaO1EaVXEfG5LfnfHAWAzw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jaO1EqVXEfG5LfnfHAWAzw" points="[-1, -9, -150, 0]$[147, -9, -2, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jaQDMKVXEfG5LfnfHAWAzw" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jaQDMaVXEfG5LfnfHAWAzw" id="(0.06666666666666667,0.5)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
