<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_wouR0KfXEfGNCsJXQCfONg" name="Proceso 1" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_wou44KfXEfGNCsJXQCfONg" name="Sistema">
      <elements xmi:type="process:Lane" xmi:id="_wou44afXEfGNCsJXQCfONg" name="Municipio" actor="_wou5K6fXEfGNCsJXQCfONg">
        <elements xmi:type="process:StartEvent" xmi:id="_wou44qfXEfGNCsJXQCfONg" name="Inicio " outgoing="_wou5G6fXEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wou446fXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wou45KfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wou45afXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wou45qfXEfGNCsJXQCfONg" name="Registrar emergencia" outgoing="_wou5HqfXEfGNCsJXQCfONg" incoming="_wou5G6fXEfGNCsJXQCfONg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wou456fXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wou46KfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wou46afXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wou46qfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wou466fXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wou47KfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wou47afXEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wou47qfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wou476fXEfGNCsJXQCfONg">
            <targetForm xmi:type="expression:Expression" xmi:id="_wou48KfXEfGNCsJXQCfONg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wou48afXEfGNCsJXQCfONg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wou48qfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_wou486fXEfGNCsJXQCfONg" name="Centro Coordinador Regional" actor="_wou5LKfXEfGNCsJXQCfONg">
        <elements xmi:type="process:ServiceTask" xmi:id="_wou49KfXEfGNCsJXQCfONg" name="Recibir alerta " outgoing="_wou5IafXEfGNCsJXQCfONg" incoming="_wou5HqfXEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wou49afXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wou49qfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wou496fXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wou4-KfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wou4-afXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wou4-qfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wou4-6fXEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wou4_KfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wou4_afXEfGNCsJXQCfONg" name="Publicar en red" outgoing="_v4Z9QKfZEfGNCsJXQCfONg" incoming="_wou5JKfXEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wou4_qfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wou4_6fXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wou5AKfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wou5AafXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wou5AqfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wou5A6fXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wou5BKfXEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wou5BafXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_wou5BqfXEfGNCsJXQCfONg" name="Desglosar en &quot;Lotes Necesidades&quot;" outgoing="_wou5JKfXEfGNCsJXQCfONg" incoming="_wou5IafXEfGNCsJXQCfONg _83PvAK17EfGuq6YN8nOhFQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wou5B6fXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wou5CKfXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wou5CafXEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wou5CqfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wou5C6fXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wou5DKfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wou5DafXEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wou5DqfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_wou5D6fXEfGNCsJXQCfONg">
            <targetForm xmi:type="expression:Expression" xmi:id="_wou5EKfXEfGNCsJXQCfONg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_wou5EafXEfGNCsJXQCfONg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_wou5EqfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_9gRmQK1tEfG64rsMLSEH8A" name="Evaluar oferta parcial" outgoing="_4JRkAK17EfGuq6YN8nOhFQ" incoming="_ZYDasKhmEfGAPrJmsJOcqg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_9gwHYK1tEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_9gvgUK1tEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_9gwHYa1tEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_9gwHYq1tEfG64rsMLSEH8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_9gwHY61tEfG64rsMLSEH8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_9gwHZK1tEfG64rsMLSEH8A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_9gwHZq1tEfG64rsMLSEH8A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_9gwHZa1tEfG64rsMLSEH8A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_9gwucK1tEfG64rsMLSEH8A">
            <targetForm xmi:type="expression:Expression" xmi:id="_9gwuca1tEfG64rsMLSEH8A" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_9gwHZ61tEfG64rsMLSEH8A"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_9gwucq1tEfG64rsMLSEH8A" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_4B58QK1xEfG64rsMLSEH8A" name="Aceptar ofertas parciales" outgoing="_6pEnQK17EfGuq6YN8nOhFQ _83PvAK17EfGuq6YN8nOhFQ" incoming="_4JRkAK17EfGuq6YN8nOhFQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_4B8Yga1xEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_4B8YgK1xEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_4B8Ygq1xEfG64rsMLSEH8A" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Kr5DUKfZEfGNCsJXQCfONg" name="ONG/ Organismo rescate">
        <elements xmi:type="process:Task" xmi:id="_NuZLAKfZEfGNCsJXQCfONg" name="Registrar / actualizar oferta de ayuda" outgoing="_LV0UoKfaEfGNCsJXQCfONg" incoming="_Nueql6fZEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NuZLAafZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NuZLAqfZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NuZLA6fZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NuZLBKfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NuZLBafZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NuZLBqfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NuZLB6fZEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NuZLCKfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_8DgJsKfwEfGNCsJXQCfONg" name="Ventana de recepción de ofertas"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_NuZLCafZEfGNCsJXQCfONg">
            <targetForm xmi:type="expression:Expression" xmi:id="_NuZLCqfZEfGNCsJXQCfONg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_NuZLC6fZEfGNCsJXQCfONg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_NuZLDKfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_NucOUKfZEfGNCsJXQCfONg" name="Recibir notificación" outgoing="_Nueql6fZEfGNCsJXQCfONg" incoming="_v4Z9QKfZEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NucOUafZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_NucOUqfZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NucOU6fZEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_NucOVKfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_NucOVafZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_NucOVqfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_NucOV6fZEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_NucOWKfZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_7E65AKfZEfGNCsJXQCfONg" name="Sistema Nacional">
        <elements xmi:type="process:ServiceTask" xmi:id="_BTMZIKfaEfGNCsJXQCfONg" name="Validar en el Sistema Nacional (POST Cloud)" outgoing="_BTQqkKfaEfGNCsJXQCfONg" incoming="_AUUF4KhlEfGAPrJmsJOcqg _6pEnQK17EfGuq6YN8nOhFQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BTMZIafaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BTMZIqfaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BTMZI6faEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BTMZp6faEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BTMZqKfaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BTMZqafaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BTMZqqfaEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BTMZq6faEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_BTOOUKfaEfGNCsJXQCfONg" name="Obtener ofertas " outgoing="__v5xQKhkEfGAPrJmsJOcqg" incoming="_LV0UoKfaEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BTOOUafaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BTOOUqfaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BTOOU6faEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BTO13afaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BTO13qfaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BTO136faEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BTO14KfaEfGNCsJXQCfONg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BTO14afaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_BTPccKfaEfGNCsJXQCfONg" name="Fin" incoming="_BTQqkKfaEfGNCsJXQCfONg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BTPccafaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BTPccqfaEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BTPcc6faEfGNCsJXQCfONg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_8kovIKhkEfGAPrJmsJOcqg" name="Cumple totalidad lotes" outgoing="_AUUF4KhlEfGAPrJmsJOcqg _ZYDasKhmEfGAPrJmsJOcqg" incoming="__v5xQKhkEfGAPrJmsJOcqg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8ku1wahkEfGAPrJmsJOcqg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8ku1wKhkEfGAPrJmsJOcqg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8ku1wqhkEfGAPrJmsJOcqg" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_wou5F6fXEfGNCsJXQCfONg">
        <targetForm xmi:type="expression:Expression" xmi:id="_wou5GKfXEfGNCsJXQCfONg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_wou5GafXEfGNCsJXQCfONg">
        <targetForm xmi:type="expression:Expression" xmi:id="_wou5GqfXEfGNCsJXQCfONg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wou5G6fXEfGNCsJXQCfONg" target="_wou45qfXEfGNCsJXQCfONg" source="_wou44qfXEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wou5HKfXEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wou5HafXEfGNCsJXQCfONg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wou5HqfXEfGNCsJXQCfONg" target="_wou49KfXEfGNCsJXQCfONg" source="_wou45qfXEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wou5H6fXEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wou5IKfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wou5IafXEfGNCsJXQCfONg" target="_wou5BqfXEfGNCsJXQCfONg" source="_wou49KfXEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wou5IqfXEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wou5I6fXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wou5JKfXEfGNCsJXQCfONg" target="_wou4_afXEfGNCsJXQCfONg" source="_wou5BqfXEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wou5JafXEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_wou5JqfXEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Nueql6fZEfGNCsJXQCfONg" target="_NuZLAKfZEfGNCsJXQCfONg" source="_NucOUKfZEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NueqmKfZEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_NueqmafZEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_v4Z9QKfZEfGNCsJXQCfONg" target="_NucOUKfZEfGNCsJXQCfONg" source="_wou4_afXEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_v4akUKfZEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_v4akUafZEfGNCsJXQCfONg" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BTQqkKfaEfGNCsJXQCfONg" target="_BTPccKfaEfGNCsJXQCfONg" source="_BTMZIKfaEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BTQqkafaEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_BTQqkqfaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LV0UoKfaEfGNCsJXQCfONg" target="_BTOOUKfaEfGNCsJXQCfONg" source="_NuZLAKfZEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LV0UoafaEfGNCsJXQCfONg"/>
        <condition xmi:type="expression:Expression" xmi:id="_LV0UoqfaEfGNCsJXQCfONg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__v5xQKhkEfGAPrJmsJOcqg" target="_8kovIKhkEfGAPrJmsJOcqg" source="_BTOOUKfaEfGNCsJXQCfONg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__v6YUKhkEfGAPrJmsJOcqg"/>
        <condition xmi:type="expression:Expression" xmi:id="__v6YUahkEfGAPrJmsJOcqg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AUUF4KhlEfGAPrJmsJOcqg" name="si" target="_BTMZIKfaEfGNCsJXQCfONg" source="_8kovIKhkEfGAPrJmsJOcqg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AUUF4ahlEfGAPrJmsJOcqg"/>
        <condition xmi:type="expression:Expression" xmi:id="_AUUF4qhlEfGAPrJmsJOcqg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZYDasKhmEfGAPrJmsJOcqg" name="no" target="_9gRmQK1tEfG64rsMLSEH8A" source="_8kovIKhkEfGAPrJmsJOcqg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZYEBwKhmEfGAPrJmsJOcqg"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZYEBwahmEfGAPrJmsJOcqg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_4JRkAK17EfGuq6YN8nOhFQ" target="_4B58QK1xEfG64rsMLSEH8A" source="_9gRmQK1tEfG64rsMLSEH8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_4JYRsK17EfGuq6YN8nOhFQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_4JY4wK17EfGuq6YN8nOhFQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6pEnQK17EfGuq6YN8nOhFQ" name="si" target="_BTMZIKfaEfGNCsJXQCfONg" source="_4B58QK1xEfG64rsMLSEH8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6pFOUK17EfGuq6YN8nOhFQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_6pFOUa17EfGuq6YN8nOhFQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_83PvAK17EfGuq6YN8nOhFQ" name="no" target="_wou5BqfXEfGNCsJXQCfONg" source="_4B58QK1xEfG64rsMLSEH8A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_83PvAa17EfGuq6YN8nOhFQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_83PvAq17EfGuq6YN8nOhFQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_wou5KqfXEfGNCsJXQCfONg" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_wou5K6fXEfGNCsJXQCfONg" name="Municipio"/>
      <actors xmi:type="process:Actor" xmi:id="_wou5LKfXEfGNCsJXQCfONg" name="Centro Coordinador Regional"/>
      <actors xmi:type="process:Actor" xmi:id="_rYoJ0KfaEfGNCsJXQCfONg" name="Empleado"/>
      <contract xmi:type="process:Contract" xmi:id="_wou5LafXEfGNCsJXQCfONg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_wou5LqfXEfGNCsJXQCfONg">
        <name xmi:type="expression:Expression" xmi:id="_wou5L6fXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_wou5MKfXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_wou5MafXEfGNCsJXQCfONg">
        <name xmi:type="expression:Expression" xmi:id="_wou5MqfXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_wou5M6fXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_wovf8KfXEfGNCsJXQCfONg">
        <name xmi:type="expression:Expression" xmi:id="_wovf8afXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_wovf8qfXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_wovf86fXEfGNCsJXQCfONg">
        <name xmi:type="expression:Expression" xmi:id="_wovf9KfXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_wovf9afXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_wovf9qfXEfGNCsJXQCfONg">
        <name xmi:type="expression:Expression" xmi:id="_wovf96fXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_wovf-KfXEfGNCsJXQCfONg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_wovf-afXEfGNCsJXQCfONg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_wovf-qfXEfGNCsJXQCfONg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_wovf-6fXEfGNCsJXQCfONg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_wovf_KfXEfGNCsJXQCfONg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_wovf_afXEfGNCsJXQCfONg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_wovf_qfXEfGNCsJXQCfONg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_wovf_6fXEfGNCsJXQCfONg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_wovgAKfXEfGNCsJXQCfONg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_wovgAafXEfGNCsJXQCfONg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_wovgAqfXEfGNCsJXQCfONg" type="Process" element="_wouR0KfXEfGNCsJXQCfONg" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_wovgA6fXEfGNCsJXQCfONg" type="2007" element="_wou44KfXEfGNCsJXQCfONg">
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgBKfXEfGNCsJXQCfONg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgBafXEfGNCsJXQCfONg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_wovgBqfXEfGNCsJXQCfONg" type="3007" element="_wou44afXEfGNCsJXQCfONg">
          <children xmi:type="notation:DecorationNode" xmi:id="_wovgB6fXEfGNCsJXQCfONg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_wovgCKfXEfGNCsJXQCfONg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_wovgCafXEfGNCsJXQCfONg" type="3005" element="_wou45qfXEfGNCsJXQCfONg" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wovgCqfXEfGNCsJXQCfONg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgC6fXEfGNCsJXQCfONg" x="128" y="68" width="179" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wovgDKfXEfGNCsJXQCfONg" type="3002" element="_wou44qfXEfGNCsJXQCfONg" fontName="Ubuntu Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_wovgDafXEfGNCsJXQCfONg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_wovgDqfXEfGNCsJXQCfONg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgD6fXEfGNCsJXQCfONg" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_wovgEKfXEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_wovgEafXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_wovgEqfXEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_wovgE6fXEfGNCsJXQCfONg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgFKfXEfGNCsJXQCfONg" x="49" y="10" width="1296" height="237"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_wovgFafXEfGNCsJXQCfONg" type="3007" element="_wou486fXEfGNCsJXQCfONg">
          <children xmi:type="notation:DecorationNode" xmi:id="_wovgFqfXEfGNCsJXQCfONg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_wovgF6fXEfGNCsJXQCfONg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_wovgGKfXEfGNCsJXQCfONg" type="3027" element="_wou49KfXEfGNCsJXQCfONg" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wovgGafXEfGNCsJXQCfONg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgGqfXEfGNCsJXQCfONg" x="174" y="67" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wovgG6fXEfGNCsJXQCfONg" type="3027" element="_wou4_afXEfGNCsJXQCfONg" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wovgHKfXEfGNCsJXQCfONg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgHafXEfGNCsJXQCfONg" x="622" y="50" width="220" height="110"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wovgHqfXEfGNCsJXQCfONg" type="3005" element="_wou5BqfXEfGNCsJXQCfONg" fontName="Ubuntu Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wovgH6fXEfGNCsJXQCfONg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgIKfXEfGNCsJXQCfONg" x="356" y="55" width="200" height="100"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_9g21EK1tEfG64rsMLSEH8A" type="3005" element="_9gRmQK1tEfG64rsMLSEH8A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_9g3cIK1tEfG64rsMLSEH8A" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_9g21Ea1tEfG64rsMLSEH8A" x="1705" y="189" width="214" height="107"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4CB4EK1xEfG64rsMLSEH8A" type="3009" element="_4B58QK1xEfG64rsMLSEH8A" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_4CDGMK1xEfG64rsMLSEH8A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_4CDGMa1xEfG64rsMLSEH8A" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4CB4Ea1xEfG64rsMLSEH8A" x="1790" y="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_wovgJafXEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_wovgJqfXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_wovgJ6fXEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_wovgKKfXEfGNCsJXQCfONg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgKafXEfGNCsJXQCfONg" x="57" y="237" width="4588" height="521"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_Kr6RcKfZEfGNCsJXQCfONg" type="3007" element="_Kr5DUKfZEfGNCsJXQCfONg">
          <children xmi:type="notation:DecorationNode" xmi:id="_Kr6RdafZEfGNCsJXQCfONg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Kr6RdqfZEfGNCsJXQCfONg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_NuZLDafZEfGNCsJXQCfONg" type="3005" element="_NuZLAKfZEfGNCsJXQCfONg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NuZLDqfZEfGNCsJXQCfONg" type="5005" element="_NuZLAKfZEfGNCsJXQCfONg"/>
              <children xmi:type="notation:Shape" xmi:id="_8DjNAKfwEfGNCsJXQCfONg" type="3043" element="_8DgJsKfwEfGNCsJXQCfONg" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_8Dj0EKfwEfGNCsJXQCfONg" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_8Dj0EafwEfGNCsJXQCfONg" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8DjNAafwEfGNCsJXQCfONg" y="121"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NuZLD6fZEfGNCsJXQCfONg" x="1146" y="49" width="258" height="129"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NucOWafZEfGNCsJXQCfONg" type="3027" element="_NucOUKfZEfGNCsJXQCfONg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_NucOWqfZEfGNCsJXQCfONg" type="5017" element="_NucOUKfZEfGNCsJXQCfONg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_NucOW6fZEfGNCsJXQCfONg" x="774" y="57" width="246" height="121"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Kr6RcafZEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Kr6RcqfZEfGNCsJXQCfONg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Kr6Rc6fZEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Kr6Rd6fZEfGNCsJXQCfONg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Kr6RdKfZEfGNCsJXQCfONg" x="57" y="787" width="1288" height="300"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_7E8HIKfZEfGNCsJXQCfONg" type="3007" element="_7E65AKfZEfGNCsJXQCfONg">
          <children xmi:type="notation:DecorationNode" xmi:id="_7E8uMKfZEfGNCsJXQCfONg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_7E8uMafZEfGNCsJXQCfONg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_BTNAMKfaEfGNCsJXQCfONg" type="3027" element="_BTMZIKfaEfGNCsJXQCfONg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BTNAMafaEfGNCsJXQCfONg" type="5017" element="_BTMZIKfaEfGNCsJXQCfONg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BTNAMqfaEfGNCsJXQCfONg" x="1953" y="58" width="284" height="142"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BTO14qfaEfGNCsJXQCfONg" type="3027" element="_BTOOUKfaEfGNCsJXQCfONg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BTO146faEfGNCsJXQCfONg" type="5017" element="_BTOOUKfaEfGNCsJXQCfONg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BTO15KfaEfGNCsJXQCfONg" x="1401" y="96" width="186" height="93"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BTPcdKfaEfGNCsJXQCfONg" type="3003" element="_BTPccKfaEfGNCsJXQCfONg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_BTPcdafaEfGNCsJXQCfONg" type="5025" element="_BTPccKfaEfGNCsJXQCfONg">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BTPcdqfaEfGNCsJXQCfONg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BTPcd6faEfGNCsJXQCfONg" x="2351" y="105"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8kygIKhkEfGAPrJmsJOcqg" type="3008" element="_8kovIKhkEfGAPrJmsJOcqg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_8kzHMKhkEfGAPrJmsJOcqg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_8kzHMahkEfGAPrJmsJOcqg" x="17" y="17"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8kygIahkEfGAPrJmsJOcqg" x="1724" y="124"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_7E8HIafZEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_7E8HIqfZEfGNCsJXQCfONg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_7E8HI6fZEfGNCsJXQCfONg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_7E8uMqfZEfGNCsJXQCfONg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7E8HJKfZEfGNCsJXQCfONg" x="57" y="1087" width="1288" height="430"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_wovgKqfXEfGNCsJXQCfONg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_wovgK6fXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_wovgLKfXEfGNCsJXQCfONg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_wovgLafXEfGNCsJXQCfONg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wovgLqfXEfGNCsJXQCfONg" width="2520" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_wovgL6fXEfGNCsJXQCfONg"/>
    <edges xmi:type="notation:Connector" xmi:id="_wovgMKfXEfGNCsJXQCfONg" type="4001" element="_wou5G6fXEfGNCsJXQCfONg" source="_wovgDKfXEfGNCsJXQCfONg" target="_wovgCafXEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgMafXEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wovgMqfXEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wovgM6fXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wovgNKfXEfGNCsJXQCfONg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wovgNafXEfGNCsJXQCfONg" type="4001" element="_wou5HqfXEfGNCsJXQCfONg" source="_wovgCafXEfGNCsJXQCfONg" target="_wovgGKfXEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgNqfXEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wovgN6fXEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wovgOKfXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wovgOafXEfGNCsJXQCfONg" points="[0, 30, 0, -194]$[-3, 214, -3, -10]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wovgOqfXEfGNCsJXQCfONg" id="(0.46,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wovgO6fXEfGNCsJXQCfONg" type="4001" element="_wou5IafXEfGNCsJXQCfONg" source="_wovgGKfXEfGNCsJXQCfONg" target="_wovgHqfXEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgPKfXEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wovgPafXEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wovgPqfXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wovgP6fXEfGNCsJXQCfONg" points="[9, -2, -99, 0]$[100, -2, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wovgQKfXEfGNCsJXQCfONg" id="(0.925,0.6333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wovgQafXEfGNCsJXQCfONg" id="(0.06666666666666667,0.5166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wovgQqfXEfGNCsJXQCfONg" type="4001" element="_wou5JKfXEfGNCsJXQCfONg" source="_wovgHqfXEfGNCsJXQCfONg" target="_wovgG6fXEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wovgQ6fXEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wovgRKfXEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wovgRafXEfGNCsJXQCfONg" fontName="Ubuntu Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wovgRqfXEfGNCsJXQCfONg" points="[9, 1, -172, 0]$[172, 1, -9, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wovgR6fXEfGNCsJXQCfONg" id="(0.925,0.4666666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wovgSKfXEfGNCsJXQCfONg" id="(0.09,0.54)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NueqmqfZEfGNCsJXQCfONg" type="4001" element="_Nueql6fZEfGNCsJXQCfONg" source="_NucOWafZEfGNCsJXQCfONg" target="_NuZLDafZEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Nueqm6fZEfGNCsJXQCfONg" type="6001" element="_Nueql6fZEfGNCsJXQCfONg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NueqnKfZEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NueqnafZEfGNCsJXQCfONg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NueqnqfZEfGNCsJXQCfONg" points="[1, 1, -175, -10]$[127, 1, -49, -10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Nueqn6fZEfGNCsJXQCfONg" id="(0.9959349593495935,0.45454545454545453)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NueqoKfZEfGNCsJXQCfONg" id="(0.18992248062015504,0.5736434108527132)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_v4cZgKfZEfGNCsJXQCfONg" type="4001" element="_v4Z9QKfZEfGNCsJXQCfONg" source="_wovgG6fXEfGNCsJXQCfONg" target="_NucOWafZEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_v4dnoKfZEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_v4dnoafZEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_v4cZgafZEfGNCsJXQCfONg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_v4cZgqfZEfGNCsJXQCfONg" points="[-80, 80, 253, -252]$[-80, 215, 253, -117]$[-272, 215, 61, -117]$[-272, 272, 61, -60]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_v4pN0KfZEfGNCsJXQCfONg" id="(1.0,0.2727272727272727)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BTQqk6faEfGNCsJXQCfONg" type="4001" element="_BTQqkKfaEfGNCsJXQCfONg" source="_BTNAMKfaEfGNCsJXQCfONg" target="_BTPcdKfaEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BTQqlKfaEfGNCsJXQCfONg" type="6001" element="_BTQqkKfaEfGNCsJXQCfONg">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BTQqlafaEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BTQqlqfaEfGNCsJXQCfONg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BTQql6faEfGNCsJXQCfONg" points="[0, 0, -84, -80]$[82, 65, -2, -15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BTQqmKfaEfGNCsJXQCfONg" id="(1.0,0.35714285714285715)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LV07sKfaEfGNCsJXQCfONg" type="4001" element="_LV0UoKfaEfGNCsJXQCfONg" source="_NuZLDafZEfGNCsJXQCfONg" target="_BTO14qfaEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LV1iwKfaEfGNCsJXQCfONg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LV1iwafaEfGNCsJXQCfONg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LV07safaEfGNCsJXQCfONg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LV07sqfaEfGNCsJXQCfONg" points="[-226, 108, 514, -245]$[-226, 188, 514, -165]$[-718, 188, 22, -165]$[-718, 342, 22, -11]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LV3X8KfaEfGNCsJXQCfONg" id="(1.0,0.16279069767441862)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LV3X8afaEfGNCsJXQCfONg" id="(0.3763440860215054,0.11827956989247312)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__v8NgKhkEfGAPrJmsJOcqg" type="4001" element="__v5xQKhkEfGAPrJmsJOcqg" source="_BTO14qfaEfGNCsJXQCfONg" target="_8kygIKhkEfGAPrJmsJOcqg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__v80kKhkEfGAPrJmsJOcqg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__v80kahkEfGAPrJmsJOcqg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__v8NgahkEfGAPrJmsJOcqg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__v8NgqhkEfGAPrJmsJOcqg" points="[0, 10, -138, 1]$[138, 11, 0, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="__v-pwKhkEfGAPrJmsJOcqg" id="(1.0,0.3118279569892473)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="__v-pwahkEfGAPrJmsJOcqg" id="(0.13953488372093023,0.3023255813953488)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AUY-YKhlEfGAPrJmsJOcqg" type="4001" element="_AUUF4KhlEfGAPrJmsJOcqg" source="_8kygIKhkEfGAPrJmsJOcqg" target="_BTNAMKfaEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AUY-Y6hlEfGAPrJmsJOcqg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AUY-ZKhlEfGAPrJmsJOcqg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AUY-YahlEfGAPrJmsJOcqg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AUY-YqhlEfGAPrJmsJOcqg" points="[-5, -11, -248, 32]$[186, -11, -57, 32]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AUazkKhlEfGAPrJmsJOcqg" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AUazkahlEfGAPrJmsJOcqg" id="(0.2007042253521127,0.3591549295774648)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZYNywKhmEfGAPrJmsJOcqg" type="4001" element="_ZYDasKhmEfGAPrJmsJOcqg" source="_8kygIKhkEfGAPrJmsJOcqg" target="_9g21EK1tEfG64rsMLSEH8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZYOZ0KhmEfGAPrJmsJOcqg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZYOZ0ahmEfGAPrJmsJOcqg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZYNywahmEfGAPrJmsJOcqg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZYNywqhmEfGAPrJmsJOcqg" points="[-22, -26, -29, 703]$[-22, -402, -29, 327]$[-6, -402, -13, 327]$[-6, -719, -13, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZYQPAKhmEfGAPrJmsJOcqg" id="(1.0,0.6046511627906976)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0P8RAKvFEfGuGNku7JKTzg" id="(0.2698412698412698,0.8412698412698413)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_4Je_YK17EfGuq6YN8nOhFQ" type="4001" element="_4JRkAK17EfGuq6YN8nOhFQ" source="_9g21EK1tEfG64rsMLSEH8A" target="_4CB4EK1xEfG64rsMLSEH8A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_4JgNgK17EfGuq6YN8nOhFQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_4JgNga17EfGuq6YN8nOhFQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_4Je_Ya17EfGuq6YN8nOhFQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_4Je_Yq17EfGuq6YN8nOhFQ" points="[-31, -22, 143, 113]$[-175, -115, -1, 20]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_4JltEK17EfGuq6YN8nOhFQ" id="(0.5046728971962616,0.1308411214953271)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6pGccK17EfGuq6YN8nOhFQ" type="4001" element="_6pEnQK17EfGuq6YN8nOhFQ" source="_4CB4EK1xEfG64rsMLSEH8A" target="_BTNAMKfaEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6pHDgK17EfGuq6YN8nOhFQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6pHDga17EfGuq6YN8nOhFQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6pGcca17EfGuq6YN8nOhFQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6pGccq17EfGuq6YN8nOhFQ" points="[-1, -4, -197, -658]$[194, 708, -2, 54]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6pL8AK17EfGuq6YN8nOhFQ" id="(1.0,0.627906976744186)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_83Q9IK17EfGuq6YN8nOhFQ" type="4001" element="_83PvAK17EfGuq6YN8nOhFQ" source="_4CB4EK1xEfG64rsMLSEH8A" target="_wovgHqfXEfGNCsJXQCfONg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_83SLQK17EfGuq6YN8nOhFQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_83SyUK17EfGuq6YN8nOhFQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_83Q9Ia17EfGuq6YN8nOhFQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_83RkMK17EfGuq6YN8nOhFQ" points="[-23, -26, 1354, -54]$[-23, -136, 1354, -164]$[-1377, -136, 0, -164]$[-1377, -22, 0, -50]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_83WcsK17EfGuq6YN8nOhFQ" id="(1.0,0.627906976744186)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
