-- RescueSync: reset total de la base + datos de ejemplo compartidos por el equipo.
-- DESTRUCTIVO: borra regiones, municipios, recursos, ONGs, emergencias y todo lo que depende de ellos
-- (lotes, ítems, ofertas, detalles, actividades, inventario). Carga el catálogo, pero deja emergencias y lotes
-- vacíos: dependen de casos de Bonita y se crean desde la app.
-- Uso (desde la raíz del repo, con el contenedor postgres_db levantado):
--   docker exec -i postgres_db psql -U postgres -d rescuesync < db/seed/01-reset-y-seed.sql
-- Correrlo ANTES de levantar el backend (adapta el esquema a las entidades Region, Municipio, Ong y Lote).

BEGIN;

-- 0) Adaptación de esquema (idempotente). Va antes del TRUNCATE para no depender de datos previos.
CREATE TABLE IF NOT EXISTS region (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  bonita_group_path varchar(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS notificacion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_destinatario varchar(50) NOT NULL,
  grupo_destinatario varchar(255) NOT NULL,
  titulo varchar(200) NOT NULL,
  descripcion varchar(1000) NOT NULL,
  remitente_user_id varchar(100) NOT NULL,
  remitente_username varchar(150),
  fecha_creacion timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS notificacion_inactiva (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notificacion_id bigint NOT NULL REFERENCES notificacion (id) ON DELETE CASCADE,
  usuario_id varchar(100) NOT NULL,
  fecha_eliminacion timestamp NOT NULL,
  CONSTRAINT uk_notificacion_usuario UNIQUE (notificacion_id, usuario_id)
);

TRUNCATE TABLE notificacion_inactiva, notificacion,
  region, municipio, recurso, ong, emergencia RESTART IDENTITY CASCADE;

ALTER TABLE notificacion ALTER COLUMN grupo_destinatario SET NOT NULL;

ALTER TABLE ong ADD COLUMN IF NOT EXISTS bonita_group_path varchar(200);
ALTER TABLE municipio ADD COLUMN IF NOT EXISTS bonita_group_path varchar(200);
ALTER TABLE municipio ADD COLUMN IF NOT EXISTS region_id bigint REFERENCES region (id);
-- La ventana de ofertas pasa de la emergencia al lote (cada publicación conserva la suya)
ALTER TABLE lote DROP COLUMN IF EXISTS fecha_inicio;
ALTER TABLE lote ADD COLUMN IF NOT EXISTS fecha_apertura_ofertas timestamp;
ALTER TABLE lote ADD COLUMN IF NOT EXISTS fecha_cierre_ofertas timestamp;
ALTER TABLE emergencia DROP COLUMN IF EXISTS fecha_apertura_ofertas;
ALTER TABLE emergencia DROP COLUMN IF EXISTS fecha_cierre_ofertas;
DROP INDEX IF EXISTS ux_lote_un_no_cancelado_por_emergencia;
-- Edición y baja lógica de ofertas. Hibernate crea el check del enum una sola vez y ddl-auto=update
-- no lo regenera: se borra para que acepte estados nuevos (ELIMINADA).
ALTER TABLE oferta ADD COLUMN IF NOT EXISTS fecha_modificacion timestamp;
ALTER TABLE oferta ADD COLUMN IF NOT EXISTS numero_version integer NOT NULL DEFAULT 0;
ALTER TABLE oferta DROP CONSTRAINT IF EXISTS oferta_estado_check;

-- 1) Regiones y municipios. Clave de negocio = path del grupo en la organización RescueSync de Bonita.
INSERT INTO region (nombre, bonita_group_path) VALUES
  ('Región 1', '/Municipio/Region1'),   -- id 1
  ('Región 2', '/Municipio/Region2'),   -- id 2
  ('Región 3', '/Municipio/Region3'),   -- id 3
  ('Región 4', '/Municipio/Region4');   -- id 4

INSERT INTO municipio (nombre, bonita_group_path, region_id) VALUES
  ('La Plata',  '/Municipio/Region1/LaPlata',  1),   -- id 1
  ('City Bell', '/Municipio/Region1/CityBell', 1),   -- id 2
  ('Berisso',   '/Municipio/Region2/Berisso',  2),   -- id 3
  ('Lobos',     '/Municipio/Region3/Lobos',    3),   -- id 4
  ('Quilmes',   '/Municipio/Region4/Quilmes',  4);   -- id 5

ALTER TABLE municipio ALTER COLUMN bonita_group_path SET NOT NULL;
ALTER TABLE municipio ALTER COLUMN region_id SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_municipio_bonita_group_path ON municipio (bonita_group_path);

INSERT INTO recurso (nombre, unidad_medida) VALUES
  ('Raciones de alimento', 'raciones'),   -- id 1
  ('Paramédicos', 'personas'),            -- id 2
  ('Frazadas', 'unidades'),               -- id 3
  ('Bombas de agua', 'unidades'),         -- id 4
  ('Agua potable', 'litros'),             -- id 5
  ('Carpas', 'unidades'),                 -- id 6
  ('Botes de rescate', 'unidades'),       -- id 7
  ('Kits de higiene', 'unidades'),        -- id 8
  ('Generadores eléctricos', 'unidades'), -- id 9
  ('Médicos', 'personas');                -- id 10

-- 2) ONGs. Clave de negocio = path del subgrupo en la organización RescueSync de Bonita.
INSERT INTO ong (razon_social, bonita_group_path) VALUES
  ('Cruz Roja Argentina – Filial La Plata',     '/ONG/CruzRojaLaPlata'),     -- id 1
  ('Cáritas Arquidiócesis de Buenos Aires',     '/ONG/CaritasBuenosAires'),  -- id 2
  ('Bomberos Voluntarios de La Plata',          '/ONG/BomberosLaPlata'),     -- id 3
  ('Fundación Banco de Alimentos Buenos Aires', '/ONG/BancoAlimentosBA'),    -- id 4
  ('Techo Argentina – Regional Buenos Aires',   '/ONG/TechoBuenosAires');    -- id 5

ALTER TABLE ong ALTER COLUMN bonita_group_path SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_ong_bonita_group_path ON ong (bonita_group_path);

-- 3) Inventario (ong_id, recurso_id, cantidad_disponible)
INSERT INTO inventario_ong (ong_id, recurso_id, cantidad_disponible) VALUES
  (1,2,10),(1,3,200),          -- Cruz Roja: paramédicos, frazadas
  (2,1,800),(2,3,150),         -- Cáritas: raciones, frazadas
  (3,2,6),(3,4,4),             -- Bomberos: paramédicos, bombas de agua
  (4,1,1500),                  -- Banco de Alimentos: raciones
  (5,3,300),(5,4,2),           -- Techo: frazadas, bombas de agua
  (1,8,500),(1,10,4),          -- Cruz Roja: kits de higiene, médicos
  (2,5,20000),(2,8,800),       -- Cáritas: agua potable, kits de higiene
  (3,7,6),(3,9,5),             -- Bomberos: botes de rescate, generadores
  (4,5,30000),                 -- Banco de Alimentos: agua potable
  (5,6,80),(5,9,3);            -- Techo: carpas, generadores

-- 4) Emergencias y lotes: SIN datos de ejemplo. Cada emergencia necesita su caso en Bonita
-- (bonita_case_id), así que se crean desde la app (municipal -> coordinador), no desde el seed.

-- Un solo lote no cancelado por emergencia, garantizado por la base
CREATE UNIQUE INDEX IF NOT EXISTS ux_lote_un_no_cancelado_por_emergencia
  ON lote (emergencia_id) WHERE estado <> 'CANCELADO';

COMMIT;
